
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int uint32_t ;
struct jme_softc {int dummy; } ;
typedef int map ;


 int CSR_WRITE_4 (struct jme_softc*,scalar_t__,int ) ;
 scalar_t__ JME_MSINUM_BASE ;
 int JME_MSI_MESSAGES ;
 int MSINUM_INTR_SOURCE (int,int ) ;
 int MSINUM_NUM_INTR_SOURCE ;
 size_t MSINUM_REG_INDEX (int ) ;
 int N_INTR_RXQ0_COAL ;
 int N_INTR_RXQ0_COAL_TO ;
 int N_INTR_RXQ0_COMP ;
 int N_INTR_RXQ0_DESC_EMPTY ;
 int N_INTR_RXQ1_COAL ;
 int N_INTR_RXQ1_COAL_TO ;
 int N_INTR_RXQ1_COMP ;
 int N_INTR_RXQ1_DESC_EMPTY ;
 int N_INTR_RXQ2_COAL ;
 int N_INTR_RXQ2_COAL_TO ;
 int N_INTR_RXQ2_COMP ;
 int N_INTR_RXQ2_DESC_EMPTY ;
 int N_INTR_RXQ3_COAL ;
 int N_INTR_RXQ3_COAL_TO ;
 int N_INTR_RXQ3_COMP ;
 int N_INTR_RXQ3_DESC_EMPTY ;
 int N_INTR_TXQ0_COMP ;
 int N_INTR_TXQ1_COMP ;
 int N_INTR_TXQ2_COMP ;
 int N_INTR_TXQ3_COMP ;
 int N_INTR_TXQ4_COMP ;
 int N_INTR_TXQ5_COMP ;
 int N_INTR_TXQ6_COMP ;
 int N_INTR_TXQ7_COMP ;
 int N_INTR_TXQ_COAL ;
 int N_INTR_TXQ_COAL_TO ;
 int bzero (int *,int) ;

__attribute__((used)) static void
jme_map_intr_vector(struct jme_softc *sc)
{
 uint32_t map[MSINUM_NUM_INTR_SOURCE / JME_MSI_MESSAGES];

 bzero(map, sizeof(map));


 map[MSINUM_REG_INDEX(N_INTR_TXQ0_COMP)] =
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ0_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ1_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ1_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ2_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ2_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ3_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ3_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ4_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ4_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ5_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ5_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ6_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ6_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ7_COMP)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ7_COMP);
 map[MSINUM_REG_INDEX(N_INTR_TXQ_COAL)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ_COAL);
 map[MSINUM_REG_INDEX(N_INTR_TXQ_COAL_TO)] |=
     MSINUM_INTR_SOURCE(2, N_INTR_TXQ_COAL_TO);


 map[MSINUM_REG_INDEX(N_INTR_RXQ0_COMP)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ0_COMP);
 map[MSINUM_REG_INDEX(N_INTR_RXQ1_COMP)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ1_COMP);
 map[MSINUM_REG_INDEX(N_INTR_RXQ2_COMP)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ2_COMP);
 map[MSINUM_REG_INDEX(N_INTR_RXQ3_COMP)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ3_COMP);
 map[MSINUM_REG_INDEX(N_INTR_RXQ0_DESC_EMPTY)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ0_DESC_EMPTY);
 map[MSINUM_REG_INDEX(N_INTR_RXQ1_DESC_EMPTY)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ1_DESC_EMPTY);
 map[MSINUM_REG_INDEX(N_INTR_RXQ2_DESC_EMPTY)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ2_DESC_EMPTY);
 map[MSINUM_REG_INDEX(N_INTR_RXQ3_DESC_EMPTY)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ3_DESC_EMPTY);
 map[MSINUM_REG_INDEX(N_INTR_RXQ0_COAL)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ0_COAL);
 map[MSINUM_REG_INDEX(N_INTR_RXQ1_COAL)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ1_COAL);
 map[MSINUM_REG_INDEX(N_INTR_RXQ2_COAL)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ2_COAL);
 map[MSINUM_REG_INDEX(N_INTR_RXQ3_COAL)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ3_COAL);
 map[MSINUM_REG_INDEX(N_INTR_RXQ0_COAL_TO)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ0_COAL_TO);
 map[MSINUM_REG_INDEX(N_INTR_RXQ1_COAL_TO)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ1_COAL_TO);
 map[MSINUM_REG_INDEX(N_INTR_RXQ2_COAL_TO)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ2_COAL_TO);
 map[MSINUM_REG_INDEX(N_INTR_RXQ3_COAL_TO)] =
     MSINUM_INTR_SOURCE(1, N_INTR_RXQ3_COAL_TO);


 CSR_WRITE_4(sc, JME_MSINUM_BASE + sizeof(uint32_t) * 0, map[0]);
 CSR_WRITE_4(sc, JME_MSINUM_BASE + sizeof(uint32_t) * 1, map[1]);
 CSR_WRITE_4(sc, JME_MSINUM_BASE + sizeof(uint32_t) * 2, map[2]);
 CSR_WRITE_4(sc, JME_MSINUM_BASE + sizeof(uint32_t) * 3, map[3]);
}
