
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct dce_hwseq {int dummy; } ;


 int DOMAIN0_PG_CONFIG ;
 int DOMAIN0_POWER_FORCEON ;
 int DOMAIN10_PG_CONFIG ;
 int DOMAIN11_PG_CONFIG ;
 int DOMAIN16_PG_CONFIG ;
 int DOMAIN16_POWER_FORCEON ;
 int DOMAIN17_PG_CONFIG ;
 int DOMAIN17_POWER_FORCEON ;
 int DOMAIN18_PG_CONFIG ;
 int DOMAIN18_POWER_FORCEON ;
 int DOMAIN19_PG_CONFIG ;
 int DOMAIN19_POWER_FORCEON ;
 int DOMAIN1_PG_CONFIG ;
 int DOMAIN1_POWER_FORCEON ;
 int DOMAIN20_PG_CONFIG ;
 int DOMAIN20_POWER_FORCEON ;
 int DOMAIN21_PG_CONFIG ;
 int DOMAIN21_POWER_FORCEON ;
 int DOMAIN2_PG_CONFIG ;
 int DOMAIN2_POWER_FORCEON ;
 int DOMAIN3_PG_CONFIG ;
 int DOMAIN3_POWER_FORCEON ;
 int DOMAIN4_PG_CONFIG ;
 int DOMAIN4_POWER_FORCEON ;
 int DOMAIN5_PG_CONFIG ;
 int DOMAIN5_POWER_FORCEON ;
 int DOMAIN6_PG_CONFIG ;
 int DOMAIN6_POWER_FORCEON ;
 int DOMAIN7_PG_CONFIG ;
 int DOMAIN7_POWER_FORCEON ;
 int DOMAIN8_PG_CONFIG ;
 int DOMAIN8_POWER_FORCEON ;
 int DOMAIN9_PG_CONFIG ;
 int DOMAIN9_POWER_FORCEON ;
 scalar_t__ REG (int ) ;
 int REG_UPDATE (int ,int ,int) ;

__attribute__((used)) static void dcn20_enable_power_gating_plane(
 struct dce_hwseq *hws,
 bool enable)
{
 bool force_on = 1;

 if (enable)
  force_on = 0;


 REG_UPDATE(DOMAIN0_PG_CONFIG, DOMAIN0_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN2_PG_CONFIG, DOMAIN2_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN4_PG_CONFIG, DOMAIN4_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN6_PG_CONFIG, DOMAIN6_POWER_FORCEON, force_on);
 if (REG(DOMAIN8_PG_CONFIG))
  REG_UPDATE(DOMAIN8_PG_CONFIG, DOMAIN8_POWER_FORCEON, force_on);
 if (REG(DOMAIN10_PG_CONFIG))
  REG_UPDATE(DOMAIN10_PG_CONFIG, DOMAIN8_POWER_FORCEON, force_on);


 REG_UPDATE(DOMAIN1_PG_CONFIG, DOMAIN1_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN3_PG_CONFIG, DOMAIN3_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN5_PG_CONFIG, DOMAIN5_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN7_PG_CONFIG, DOMAIN7_POWER_FORCEON, force_on);
 if (REG(DOMAIN9_PG_CONFIG))
  REG_UPDATE(DOMAIN9_PG_CONFIG, DOMAIN9_POWER_FORCEON, force_on);
 if (REG(DOMAIN11_PG_CONFIG))
  REG_UPDATE(DOMAIN11_PG_CONFIG, DOMAIN9_POWER_FORCEON, force_on);


 REG_UPDATE(DOMAIN16_PG_CONFIG, DOMAIN16_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN17_PG_CONFIG, DOMAIN17_POWER_FORCEON, force_on);
 REG_UPDATE(DOMAIN18_PG_CONFIG, DOMAIN18_POWER_FORCEON, force_on);
 if (REG(DOMAIN19_PG_CONFIG))
  REG_UPDATE(DOMAIN19_PG_CONFIG, DOMAIN19_POWER_FORCEON, force_on);
 if (REG(DOMAIN20_PG_CONFIG))
  REG_UPDATE(DOMAIN20_PG_CONFIG, DOMAIN20_POWER_FORCEON, force_on);
 if (REG(DOMAIN21_PG_CONFIG))
  REG_UPDATE(DOMAIN21_PG_CONFIG, DOMAIN21_POWER_FORCEON, force_on);
}
