
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct mcif_wb {int dummy; } ;
struct mcif_arb_params {int time_per_pixel; int* cli_watermark; int* pstate_watermark; int max_scaled_time; int slice_lines; int arbitration_slice; } ;
struct dcn20_mmhubbub {int dummy; } ;


 int MAX_SCALED_TIME_TO_URGENT ;
 int MCIF_WB_ARBITRATION_CONTROL ;
 int MCIF_WB_BUFMGR_SLICE_SIZE ;
 int MCIF_WB_BUFMGR_VCE_CONTROL ;
 int MCIF_WB_CLIENT_ARBITRATION_SLICE ;
 int MCIF_WB_CLI_WATERMARK ;
 int MCIF_WB_CLI_WATERMARK_MASK ;
 int MCIF_WB_NB_PSTATE_CONTROL ;
 int MCIF_WB_NB_PSTATE_LATENCY_WATERMARK ;
 int MCIF_WB_SCLK_CHANGE ;
 int MCIF_WB_TIME_PER_PIXEL ;
 int MCIF_WB_WATERMARK ;
 int MULTI_LEVEL_QOS_CTRL ;
 int NB_PSTATE_CHANGE_REFRESH_WATERMARK ;
 int NB_PSTATE_CHANGE_WATERMARK_MASK ;
 int REG_UPDATE (int ,int ,int) ;
 struct dcn20_mmhubbub* TO_DCN20_MMHUBBUB (struct mcif_wb*) ;

__attribute__((used)) static void mmhubbub2_config_mcif_arb(struct mcif_wb *mcif_wb,
  struct mcif_arb_params *params)
{
 struct dcn20_mmhubbub *mcif_wb20 = TO_DCN20_MMHUBBUB(mcif_wb);


 REG_UPDATE(MCIF_WB_ARBITRATION_CONTROL, MCIF_WB_TIME_PER_PIXEL, params->time_per_pixel);




 REG_UPDATE(MCIF_WB_SCLK_CHANGE, MCIF_WB_CLI_WATERMARK_MASK, 0x0);

 REG_UPDATE(MCIF_WB_WATERMARK, MCIF_WB_CLI_WATERMARK, params->cli_watermark[0]);
 REG_UPDATE(MCIF_WB_SCLK_CHANGE, MCIF_WB_CLI_WATERMARK_MASK, 0x1);

 REG_UPDATE(MCIF_WB_WATERMARK, MCIF_WB_CLI_WATERMARK, params->cli_watermark[1]);
 REG_UPDATE(MCIF_WB_SCLK_CHANGE, MCIF_WB_CLI_WATERMARK_MASK, 0x2);

 REG_UPDATE(MCIF_WB_WATERMARK, MCIF_WB_CLI_WATERMARK, params->cli_watermark[2]);
 REG_UPDATE(MCIF_WB_SCLK_CHANGE, MCIF_WB_CLI_WATERMARK_MASK, 0x3);

 REG_UPDATE(MCIF_WB_WATERMARK, MCIF_WB_CLI_WATERMARK, params->cli_watermark[3]);



 REG_UPDATE(MCIF_WB_NB_PSTATE_CONTROL, NB_PSTATE_CHANGE_WATERMARK_MASK, 0x0);
 REG_UPDATE(MCIF_WB_NB_PSTATE_LATENCY_WATERMARK,
   NB_PSTATE_CHANGE_REFRESH_WATERMARK, params->pstate_watermark[0]);

 REG_UPDATE(MCIF_WB_NB_PSTATE_CONTROL, NB_PSTATE_CHANGE_WATERMARK_MASK, 0x1);
 REG_UPDATE(MCIF_WB_NB_PSTATE_LATENCY_WATERMARK,
   NB_PSTATE_CHANGE_REFRESH_WATERMARK, params->pstate_watermark[1]);

 REG_UPDATE(MCIF_WB_NB_PSTATE_CONTROL, NB_PSTATE_CHANGE_WATERMARK_MASK, 0x2);
 REG_UPDATE(MCIF_WB_NB_PSTATE_LATENCY_WATERMARK,
   NB_PSTATE_CHANGE_REFRESH_WATERMARK, params->pstate_watermark[2]);

 REG_UPDATE(MCIF_WB_NB_PSTATE_CONTROL, NB_PSTATE_CHANGE_WATERMARK_MASK, 0x3);
 REG_UPDATE(MCIF_WB_NB_PSTATE_LATENCY_WATERMARK,
   NB_PSTATE_CHANGE_REFRESH_WATERMARK, params->pstate_watermark[3]);


 REG_UPDATE(MULTI_LEVEL_QOS_CTRL, MAX_SCALED_TIME_TO_URGENT, params->max_scaled_time);


 REG_UPDATE(MCIF_WB_BUFMGR_VCE_CONTROL, MCIF_WB_BUFMGR_SLICE_SIZE, params->slice_lines-1);




 REG_UPDATE(MCIF_WB_ARBITRATION_CONTROL, MCIF_WB_CLIENT_ARBITRATION_SLICE, params->arbitration_slice);
}
