
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int cloudabi_rights_t ;
typedef int cloudabi_filetype_t ;
 int CLOUDABI_RIGHT_FD_DATASYNC ;
 int CLOUDABI_RIGHT_FD_READ ;
 int CLOUDABI_RIGHT_FD_SEEK ;
 int CLOUDABI_RIGHT_FD_STAT_PUT_FLAGS ;
 int CLOUDABI_RIGHT_FD_SYNC ;
 int CLOUDABI_RIGHT_FD_TELL ;
 int CLOUDABI_RIGHT_FD_WRITE ;
 int CLOUDABI_RIGHT_FILE_ADVISE ;
 int CLOUDABI_RIGHT_FILE_ALLOCATE ;
 int CLOUDABI_RIGHT_FILE_CREATE_DIRECTORY ;
 int CLOUDABI_RIGHT_FILE_CREATE_FILE ;
 int CLOUDABI_RIGHT_FILE_LINK_SOURCE ;
 int CLOUDABI_RIGHT_FILE_LINK_TARGET ;
 int CLOUDABI_RIGHT_FILE_OPEN ;
 int CLOUDABI_RIGHT_FILE_READDIR ;
 int CLOUDABI_RIGHT_FILE_READLINK ;
 int CLOUDABI_RIGHT_FILE_RENAME_SOURCE ;
 int CLOUDABI_RIGHT_FILE_RENAME_TARGET ;
 int CLOUDABI_RIGHT_FILE_STAT_FGET ;
 int CLOUDABI_RIGHT_FILE_STAT_FPUT_SIZE ;
 int CLOUDABI_RIGHT_FILE_STAT_FPUT_TIMES ;
 int CLOUDABI_RIGHT_FILE_STAT_GET ;
 int CLOUDABI_RIGHT_FILE_STAT_PUT_TIMES ;
 int CLOUDABI_RIGHT_FILE_SYMLINK ;
 int CLOUDABI_RIGHT_FILE_UNLINK ;
 int CLOUDABI_RIGHT_MEM_MAP ;
 int CLOUDABI_RIGHT_MEM_MAP_EXEC ;
 int CLOUDABI_RIGHT_POLL_FD_READWRITE ;
 int CLOUDABI_RIGHT_PROC_EXEC ;
 int CLOUDABI_RIGHT_SOCK_SHUTDOWN ;

void
cloudabi_remove_conflicting_rights(cloudabi_filetype_t filetype,
    cloudabi_rights_t *base, cloudabi_rights_t *inheriting)
{
 switch (filetype) {
 case 133:
  *base &= CLOUDABI_RIGHT_FD_STAT_PUT_FLAGS |
      CLOUDABI_RIGHT_FD_SYNC | CLOUDABI_RIGHT_FILE_ADVISE |
      CLOUDABI_RIGHT_FILE_CREATE_DIRECTORY |
      CLOUDABI_RIGHT_FILE_CREATE_FILE |
      CLOUDABI_RIGHT_FILE_LINK_SOURCE |
      CLOUDABI_RIGHT_FILE_LINK_TARGET |
      CLOUDABI_RIGHT_FILE_OPEN |
      CLOUDABI_RIGHT_FILE_READDIR |
      CLOUDABI_RIGHT_FILE_READLINK |
      CLOUDABI_RIGHT_FILE_RENAME_SOURCE |
      CLOUDABI_RIGHT_FILE_RENAME_TARGET |
      CLOUDABI_RIGHT_FILE_STAT_FGET |
      CLOUDABI_RIGHT_FILE_STAT_FPUT_TIMES |
      CLOUDABI_RIGHT_FILE_STAT_GET |
      CLOUDABI_RIGHT_FILE_STAT_PUT_TIMES |
      CLOUDABI_RIGHT_FILE_SYMLINK |
      CLOUDABI_RIGHT_FILE_UNLINK |
      CLOUDABI_RIGHT_POLL_FD_READWRITE;
  *inheriting &= CLOUDABI_RIGHT_FD_DATASYNC |
      CLOUDABI_RIGHT_FD_READ |
      CLOUDABI_RIGHT_FD_SEEK |
      CLOUDABI_RIGHT_FD_STAT_PUT_FLAGS |
      CLOUDABI_RIGHT_FD_SYNC |
      CLOUDABI_RIGHT_FD_TELL |
      CLOUDABI_RIGHT_FD_WRITE |
      CLOUDABI_RIGHT_FILE_ADVISE |
      CLOUDABI_RIGHT_FILE_ALLOCATE |
      CLOUDABI_RIGHT_FILE_CREATE_DIRECTORY |
      CLOUDABI_RIGHT_FILE_CREATE_FILE |
      CLOUDABI_RIGHT_FILE_LINK_SOURCE |
      CLOUDABI_RIGHT_FILE_LINK_TARGET |
      CLOUDABI_RIGHT_FILE_OPEN |
      CLOUDABI_RIGHT_FILE_READDIR |
      CLOUDABI_RIGHT_FILE_READLINK |
      CLOUDABI_RIGHT_FILE_RENAME_SOURCE |
      CLOUDABI_RIGHT_FILE_RENAME_TARGET |
      CLOUDABI_RIGHT_FILE_STAT_FGET |
      CLOUDABI_RIGHT_FILE_STAT_FPUT_SIZE |
      CLOUDABI_RIGHT_FILE_STAT_FPUT_TIMES |
      CLOUDABI_RIGHT_FILE_STAT_GET |
      CLOUDABI_RIGHT_FILE_STAT_PUT_TIMES |
      CLOUDABI_RIGHT_FILE_SYMLINK |
      CLOUDABI_RIGHT_FILE_UNLINK |
      CLOUDABI_RIGHT_MEM_MAP |
      CLOUDABI_RIGHT_MEM_MAP_EXEC |
      CLOUDABI_RIGHT_POLL_FD_READWRITE |
      CLOUDABI_RIGHT_PROC_EXEC;
  break;
 case 132:
  *base &= ~(CLOUDABI_RIGHT_FILE_ADVISE |
      CLOUDABI_RIGHT_POLL_FD_READWRITE);
  *inheriting = 0;
  break;
 case 131:
  *base &= CLOUDABI_RIGHT_FD_DATASYNC |
      CLOUDABI_RIGHT_FD_READ |
      CLOUDABI_RIGHT_FD_SEEK |
      CLOUDABI_RIGHT_FD_STAT_PUT_FLAGS |
      CLOUDABI_RIGHT_FD_SYNC |
      CLOUDABI_RIGHT_FD_TELL |
      CLOUDABI_RIGHT_FD_WRITE |
      CLOUDABI_RIGHT_FILE_ADVISE |
      CLOUDABI_RIGHT_FILE_ALLOCATE |
      CLOUDABI_RIGHT_FILE_STAT_FGET |
      CLOUDABI_RIGHT_FILE_STAT_FPUT_SIZE |
      CLOUDABI_RIGHT_FILE_STAT_FPUT_TIMES |
      CLOUDABI_RIGHT_MEM_MAP |
      CLOUDABI_RIGHT_MEM_MAP_EXEC |
      CLOUDABI_RIGHT_POLL_FD_READWRITE |
      CLOUDABI_RIGHT_PROC_EXEC;
  *inheriting = 0;
  break;
 case 130:
  *base &= ~(CLOUDABI_RIGHT_FD_SEEK |
      CLOUDABI_RIGHT_FD_TELL |
      CLOUDABI_RIGHT_FILE_ADVISE |
      CLOUDABI_RIGHT_FILE_ALLOCATE |
      CLOUDABI_RIGHT_FILE_READDIR);
  *inheriting = 0;
  break;
 case 129:
 case 128:
  *base &= CLOUDABI_RIGHT_FD_READ |
      CLOUDABI_RIGHT_FD_STAT_PUT_FLAGS |
      CLOUDABI_RIGHT_FD_WRITE |
      CLOUDABI_RIGHT_FILE_STAT_FGET |
      CLOUDABI_RIGHT_POLL_FD_READWRITE |
      CLOUDABI_RIGHT_SOCK_SHUTDOWN;
  break;
 default:
  *inheriting = 0;
  break;
 }
}
