
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_2__ TYPE_1__ ;


struct TYPE_2__ {int * OpenGLLib; } ;


 int dlclose (int *) ;
 TYPE_1__ glw_state ;
 int * qfxMesaCreateBestContext ;
 int * qfxMesaCreateContext ;
 int * qfxMesaDestroyContext ;
 int * qfxMesaGetCurrentContext ;
 int * qfxMesaMakeCurrent ;
 int * qfxMesaSwapBuffers ;
 int * qglAccum ;
 int * qglAlphaFunc ;
 int * qglAreTexturesResident ;
 int * qglArrayElement ;
 int * qglBegin ;
 int * qglBindTexture ;
 int * qglBitmap ;
 int * qglBlendFunc ;
 int * qglCallList ;
 int * qglCallLists ;
 int * qglClear ;
 int * qglClearAccum ;
 int * qglClearColor ;
 int * qglClearDepth ;
 int * qglClearIndex ;
 int * qglClearStencil ;
 int * qglClipPlane ;
 int * qglColor3b ;
 int * qglColor3bv ;
 int * qglColor3d ;
 int * qglColor3dv ;
 int * qglColor3f ;
 int * qglColor3fv ;
 int * qglColor3i ;
 int * qglColor3iv ;
 int * qglColor3s ;
 int * qglColor3sv ;
 int * qglColor3ub ;
 int * qglColor3ubv ;
 int * qglColor3ui ;
 int * qglColor3uiv ;
 int * qglColor3us ;
 int * qglColor3usv ;
 int * qglColor4b ;
 int * qglColor4bv ;
 int * qglColor4d ;
 int * qglColor4dv ;
 int * qglColor4f ;
 int * qglColor4fv ;
 int * qglColor4i ;
 int * qglColor4iv ;
 int * qglColor4s ;
 int * qglColor4sv ;
 int * qglColor4ub ;
 int * qglColor4ubv ;
 int * qglColor4ui ;
 int * qglColor4uiv ;
 int * qglColor4us ;
 int * qglColor4usv ;
 int * qglColorMask ;
 int * qglColorMaterial ;
 int * qglColorPointer ;
 int * qglCopyPixels ;
 int * qglCopyTexImage1D ;
 int * qglCopyTexImage2D ;
 int * qglCopyTexSubImage1D ;
 int * qglCopyTexSubImage2D ;
 int * qglCullFace ;
 int * qglDeleteLists ;
 int * qglDeleteTextures ;
 int * qglDepthFunc ;
 int * qglDepthMask ;
 int * qglDepthRange ;
 int * qglDisable ;
 int * qglDisableClientState ;
 int * qglDrawArrays ;
 int * qglDrawBuffer ;
 int * qglDrawElements ;
 int * qglDrawPixels ;
 int * qglEdgeFlag ;
 int * qglEdgeFlagPointer ;
 int * qglEdgeFlagv ;
 int * qglEnable ;
 int * qglEnableClientState ;
 int * qglEnd ;
 int * qglEndList ;
 int * qglEvalCoord1d ;
 int * qglEvalCoord1dv ;
 int * qglEvalCoord1f ;
 int * qglEvalCoord1fv ;
 int * qglEvalCoord2d ;
 int * qglEvalCoord2dv ;
 int * qglEvalCoord2f ;
 int * qglEvalCoord2fv ;
 int * qglEvalMesh1 ;
 int * qglEvalMesh2 ;
 int * qglEvalPoint1 ;
 int * qglEvalPoint2 ;
 int * qglFeedbackBuffer ;
 int * qglFinish ;
 int * qglFlush ;
 int * qglFogf ;
 int * qglFogfv ;
 int * qglFogi ;
 int * qglFogiv ;
 int * qglFrontFace ;
 int * qglFrustum ;
 int * qglGenLists ;
 int * qglGenTextures ;
 int * qglGetBooleanv ;
 int * qglGetClipPlane ;
 int * qglGetDoublev ;
 int * qglGetError ;
 int * qglGetFloatv ;
 int * qglGetIntegerv ;
 int * qglGetLightfv ;
 int * qglGetLightiv ;
 int * qglGetMapdv ;
 int * qglGetMapfv ;
 int * qglGetMapiv ;
 int * qglGetMaterialfv ;
 int * qglGetMaterialiv ;
 int * qglGetPixelMapfv ;
 int * qglGetPixelMapuiv ;
 int * qglGetPixelMapusv ;
 int * qglGetPointerv ;
 int * qglGetPolygonStipple ;
 int * qglGetString ;
 int * qglGetTexEnvfv ;
 int * qglGetTexEnviv ;
 int * qglGetTexGendv ;
 int * qglGetTexGenfv ;
 int * qglGetTexGeniv ;
 int * qglGetTexImage ;
 int * qglGetTexLevelParameterfv ;
 int * qglGetTexLevelParameteriv ;
 int * qglGetTexParameterfv ;
 int * qglGetTexParameteriv ;
 int * qglHint ;
 int * qglIndexMask ;
 int * qglIndexPointer ;
 int * qglIndexd ;
 int * qglIndexdv ;
 int * qglIndexf ;
 int * qglIndexfv ;
 int * qglIndexi ;
 int * qglIndexiv ;
 int * qglIndexs ;
 int * qglIndexsv ;
 int * qglIndexub ;
 int * qglIndexubv ;
 int * qglInitNames ;
 int * qglInterleavedArrays ;
 int * qglIsEnabled ;
 int * qglIsList ;
 int * qglIsTexture ;
 int * qglLightModelf ;
 int * qglLightModelfv ;
 int * qglLightModeli ;
 int * qglLightModeliv ;
 int * qglLightf ;
 int * qglLightfv ;
 int * qglLighti ;
 int * qglLightiv ;
 int * qglLineStipple ;
 int * qglLineWidth ;
 int * qglListBase ;
 int * qglLoadIdentity ;
 int * qglLoadMatrixd ;
 int * qglLoadMatrixf ;
 int * qglLoadName ;
 int * qglLogicOp ;
 int * qglMap1d ;
 int * qglMap1f ;
 int * qglMap2d ;
 int * qglMap2f ;
 int * qglMapGrid1d ;
 int * qglMapGrid1f ;
 int * qglMapGrid2d ;
 int * qglMapGrid2f ;
 int * qglMaterialf ;
 int * qglMaterialfv ;
 int * qglMateriali ;
 int * qglMaterialiv ;
 int * qglMatrixMode ;
 int * qglMultMatrixd ;
 int * qglMultMatrixf ;
 int * qglNewList ;
 int * qglNormal3b ;
 int * qglNormal3bv ;
 int * qglNormal3d ;
 int * qglNormal3dv ;
 int * qglNormal3f ;
 int * qglNormal3fv ;
 int * qglNormal3i ;
 int * qglNormal3iv ;
 int * qglNormal3s ;
 int * qglNormal3sv ;
 int * qglNormalPointer ;
 int * qglOrtho ;
 int * qglPassThrough ;
 int * qglPixelMapfv ;
 int * qglPixelMapuiv ;
 int * qglPixelMapusv ;
 int * qglPixelStoref ;
 int * qglPixelStorei ;
 int * qglPixelTransferf ;
 int * qglPixelTransferi ;
 int * qglPixelZoom ;
 int * qglPointSize ;
 int * qglPolygonMode ;
 int * qglPolygonOffset ;
 int * qglPolygonStipple ;
 int * qglPopAttrib ;
 int * qglPopClientAttrib ;
 int * qglPopMatrix ;
 int * qglPopName ;
 int * qglPrioritizeTextures ;
 int * qglPushAttrib ;
 int * qglPushClientAttrib ;
 int * qglPushMatrix ;
 int * qglPushName ;
 int * qglRasterPos2d ;
 int * qglRasterPos2dv ;
 int * qglRasterPos2f ;
 int * qglRasterPos2fv ;
 int * qglRasterPos2i ;
 int * qglRasterPos2iv ;
 int * qglRasterPos2s ;
 int * qglRasterPos2sv ;
 int * qglRasterPos3d ;
 int * qglRasterPos3dv ;
 int * qglRasterPos3f ;
 int * qglRasterPos3fv ;
 int * qglRasterPos3i ;
 int * qglRasterPos3iv ;
 int * qglRasterPos3s ;
 int * qglRasterPos3sv ;
 int * qglRasterPos4d ;
 int * qglRasterPos4dv ;
 int * qglRasterPos4f ;
 int * qglRasterPos4fv ;
 int * qglRasterPos4i ;
 int * qglRasterPos4iv ;
 int * qglRasterPos4s ;
 int * qglRasterPos4sv ;
 int * qglReadBuffer ;
 int * qglReadPixels ;
 int * qglRectd ;
 int * qglRectdv ;
 int * qglRectf ;
 int * qglRectfv ;
 int * qglRecti ;
 int * qglRectiv ;
 int * qglRects ;
 int * qglRectsv ;
 int * qglRenderMode ;
 int * qglRotated ;
 int * qglRotatef ;
 int * qglScaled ;
 int * qglScalef ;
 int * qglScissor ;
 int * qglSelectBuffer ;
 int * qglShadeModel ;
 int * qglStencilFunc ;
 int * qglStencilMask ;
 int * qglStencilOp ;
 int * qglTexCoord1d ;
 int * qglTexCoord1dv ;
 int * qglTexCoord1f ;
 int * qglTexCoord1fv ;
 int * qglTexCoord1i ;
 int * qglTexCoord1iv ;
 int * qglTexCoord1s ;
 int * qglTexCoord1sv ;
 int * qglTexCoord2d ;
 int * qglTexCoord2dv ;
 int * qglTexCoord2f ;
 int * qglTexCoord2fv ;
 int * qglTexCoord2i ;
 int * qglTexCoord2iv ;
 int * qglTexCoord2s ;
 int * qglTexCoord2sv ;
 int * qglTexCoord3d ;
 int * qglTexCoord3dv ;
 int * qglTexCoord3f ;
 int * qglTexCoord3fv ;
 int * qglTexCoord3i ;
 int * qglTexCoord3iv ;
 int * qglTexCoord3s ;
 int * qglTexCoord3sv ;
 int * qglTexCoord4d ;
 int * qglTexCoord4dv ;
 int * qglTexCoord4f ;
 int * qglTexCoord4fv ;
 int * qglTexCoord4i ;
 int * qglTexCoord4iv ;
 int * qglTexCoord4s ;
 int * qglTexCoord4sv ;
 int * qglTexCoordPointer ;
 int * qglTexEnvf ;
 int * qglTexEnvfv ;
 int * qglTexEnvi ;
 int * qglTexEnviv ;
 int * qglTexGend ;
 int * qglTexGendv ;
 int * qglTexGenf ;
 int * qglTexGenfv ;
 int * qglTexGeni ;
 int * qglTexGeniv ;
 int * qglTexImage1D ;
 int * qglTexImage2D ;
 int * qglTexParameterf ;
 int * qglTexParameterfv ;
 int * qglTexParameteri ;
 int * qglTexParameteriv ;
 int * qglTexSubImage1D ;
 int * qglTexSubImage2D ;
 int * qglTranslated ;
 int * qglTranslatef ;
 int * qglVertex2d ;
 int * qglVertex2dv ;
 int * qglVertex2f ;
 int * qglVertex2fv ;
 int * qglVertex2i ;
 int * qglVertex2iv ;
 int * qglVertex2s ;
 int * qglVertex2sv ;
 int * qglVertex3d ;
 int * qglVertex3dv ;
 int * qglVertex3f ;
 int * qglVertex3fv ;
 int * qglVertex3i ;
 int * qglVertex3iv ;
 int * qglVertex3s ;
 int * qglVertex3sv ;
 int * qglVertex4d ;
 int * qglVertex4dv ;
 int * qglVertex4f ;
 int * qglVertex4fv ;
 int * qglVertex4i ;
 int * qglVertex4iv ;
 int * qglVertex4s ;
 int * qglVertex4sv ;
 int * qglVertexPointer ;
 int * qglViewport ;
 int * qglXChooseVisual ;
 int * qglXCopyContext ;
 int * qglXCreateContext ;
 int * qglXDestroyContext ;
 int * qglXMakeCurrent ;
 int * qglXSwapBuffers ;

void QGL_Shutdown( void )
{
 if ( glw_state.OpenGLLib )
 {
  dlclose ( glw_state.OpenGLLib );
  glw_state.OpenGLLib = ((void*)0);
 }

 glw_state.OpenGLLib = ((void*)0);

 qglAccum = ((void*)0);
 qglAlphaFunc = ((void*)0);
 qglAreTexturesResident = ((void*)0);
 qglArrayElement = ((void*)0);
 qglBegin = ((void*)0);
 qglBindTexture = ((void*)0);
 qglBitmap = ((void*)0);
 qglBlendFunc = ((void*)0);
 qglCallList = ((void*)0);
 qglCallLists = ((void*)0);
 qglClear = ((void*)0);
 qglClearAccum = ((void*)0);
 qglClearColor = ((void*)0);
 qglClearDepth = ((void*)0);
 qglClearIndex = ((void*)0);
 qglClearStencil = ((void*)0);
 qglClipPlane = ((void*)0);
 qglColor3b = ((void*)0);
 qglColor3bv = ((void*)0);
 qglColor3d = ((void*)0);
 qglColor3dv = ((void*)0);
 qglColor3f = ((void*)0);
 qglColor3fv = ((void*)0);
 qglColor3i = ((void*)0);
 qglColor3iv = ((void*)0);
 qglColor3s = ((void*)0);
 qglColor3sv = ((void*)0);
 qglColor3ub = ((void*)0);
 qglColor3ubv = ((void*)0);
 qglColor3ui = ((void*)0);
 qglColor3uiv = ((void*)0);
 qglColor3us = ((void*)0);
 qglColor3usv = ((void*)0);
 qglColor4b = ((void*)0);
 qglColor4bv = ((void*)0);
 qglColor4d = ((void*)0);
 qglColor4dv = ((void*)0);
 qglColor4f = ((void*)0);
 qglColor4fv = ((void*)0);
 qglColor4i = ((void*)0);
 qglColor4iv = ((void*)0);
 qglColor4s = ((void*)0);
 qglColor4sv = ((void*)0);
 qglColor4ub = ((void*)0);
 qglColor4ubv = ((void*)0);
 qglColor4ui = ((void*)0);
 qglColor4uiv = ((void*)0);
 qglColor4us = ((void*)0);
 qglColor4usv = ((void*)0);
 qglColorMask = ((void*)0);
 qglColorMaterial = ((void*)0);
 qglColorPointer = ((void*)0);
 qglCopyPixels = ((void*)0);
 qglCopyTexImage1D = ((void*)0);
 qglCopyTexImage2D = ((void*)0);
 qglCopyTexSubImage1D = ((void*)0);
 qglCopyTexSubImage2D = ((void*)0);
 qglCullFace = ((void*)0);
 qglDeleteLists = ((void*)0);
 qglDeleteTextures = ((void*)0);
 qglDepthFunc = ((void*)0);
 qglDepthMask = ((void*)0);
 qglDepthRange = ((void*)0);
 qglDisable = ((void*)0);
 qglDisableClientState = ((void*)0);
 qglDrawArrays = ((void*)0);
 qglDrawBuffer = ((void*)0);
 qglDrawElements = ((void*)0);
 qglDrawPixels = ((void*)0);
 qglEdgeFlag = ((void*)0);
 qglEdgeFlagPointer = ((void*)0);
 qglEdgeFlagv = ((void*)0);
 qglEnable = ((void*)0);
 qglEnableClientState = ((void*)0);
 qglEnd = ((void*)0);
 qglEndList = ((void*)0);
 qglEvalCoord1d = ((void*)0);
 qglEvalCoord1dv = ((void*)0);
 qglEvalCoord1f = ((void*)0);
 qglEvalCoord1fv = ((void*)0);
 qglEvalCoord2d = ((void*)0);
 qglEvalCoord2dv = ((void*)0);
 qglEvalCoord2f = ((void*)0);
 qglEvalCoord2fv = ((void*)0);
 qglEvalMesh1 = ((void*)0);
 qglEvalMesh2 = ((void*)0);
 qglEvalPoint1 = ((void*)0);
 qglEvalPoint2 = ((void*)0);
 qglFeedbackBuffer = ((void*)0);
 qglFinish = ((void*)0);
 qglFlush = ((void*)0);
 qglFogf = ((void*)0);
 qglFogfv = ((void*)0);
 qglFogi = ((void*)0);
 qglFogiv = ((void*)0);
 qglFrontFace = ((void*)0);
 qglFrustum = ((void*)0);
 qglGenLists = ((void*)0);
 qglGenTextures = ((void*)0);
 qglGetBooleanv = ((void*)0);
 qglGetClipPlane = ((void*)0);
 qglGetDoublev = ((void*)0);
 qglGetError = ((void*)0);
 qglGetFloatv = ((void*)0);
 qglGetIntegerv = ((void*)0);
 qglGetLightfv = ((void*)0);
 qglGetLightiv = ((void*)0);
 qglGetMapdv = ((void*)0);
 qglGetMapfv = ((void*)0);
 qglGetMapiv = ((void*)0);
 qglGetMaterialfv = ((void*)0);
 qglGetMaterialiv = ((void*)0);
 qglGetPixelMapfv = ((void*)0);
 qglGetPixelMapuiv = ((void*)0);
 qglGetPixelMapusv = ((void*)0);
 qglGetPointerv = ((void*)0);
 qglGetPolygonStipple = ((void*)0);
 qglGetString = ((void*)0);
 qglGetTexEnvfv = ((void*)0);
 qglGetTexEnviv = ((void*)0);
 qglGetTexGendv = ((void*)0);
 qglGetTexGenfv = ((void*)0);
 qglGetTexGeniv = ((void*)0);
 qglGetTexImage = ((void*)0);
 qglGetTexLevelParameterfv = ((void*)0);
 qglGetTexLevelParameteriv = ((void*)0);
 qglGetTexParameterfv = ((void*)0);
 qglGetTexParameteriv = ((void*)0);
 qglHint = ((void*)0);
 qglIndexMask = ((void*)0);
 qglIndexPointer = ((void*)0);
 qglIndexd = ((void*)0);
 qglIndexdv = ((void*)0);
 qglIndexf = ((void*)0);
 qglIndexfv = ((void*)0);
 qglIndexi = ((void*)0);
 qglIndexiv = ((void*)0);
 qglIndexs = ((void*)0);
 qglIndexsv = ((void*)0);
 qglIndexub = ((void*)0);
 qglIndexubv = ((void*)0);
 qglInitNames = ((void*)0);
 qglInterleavedArrays = ((void*)0);
 qglIsEnabled = ((void*)0);
 qglIsList = ((void*)0);
 qglIsTexture = ((void*)0);
 qglLightModelf = ((void*)0);
 qglLightModelfv = ((void*)0);
 qglLightModeli = ((void*)0);
 qglLightModeliv = ((void*)0);
 qglLightf = ((void*)0);
 qglLightfv = ((void*)0);
 qglLighti = ((void*)0);
 qglLightiv = ((void*)0);
 qglLineStipple = ((void*)0);
 qglLineWidth = ((void*)0);
 qglListBase = ((void*)0);
 qglLoadIdentity = ((void*)0);
 qglLoadMatrixd = ((void*)0);
 qglLoadMatrixf = ((void*)0);
 qglLoadName = ((void*)0);
 qglLogicOp = ((void*)0);
 qglMap1d = ((void*)0);
 qglMap1f = ((void*)0);
 qglMap2d = ((void*)0);
 qglMap2f = ((void*)0);
 qglMapGrid1d = ((void*)0);
 qglMapGrid1f = ((void*)0);
 qglMapGrid2d = ((void*)0);
 qglMapGrid2f = ((void*)0);
 qglMaterialf = ((void*)0);
 qglMaterialfv = ((void*)0);
 qglMateriali = ((void*)0);
 qglMaterialiv = ((void*)0);
 qglMatrixMode = ((void*)0);
 qglMultMatrixd = ((void*)0);
 qglMultMatrixf = ((void*)0);
 qglNewList = ((void*)0);
 qglNormal3b = ((void*)0);
 qglNormal3bv = ((void*)0);
 qglNormal3d = ((void*)0);
 qglNormal3dv = ((void*)0);
 qglNormal3f = ((void*)0);
 qglNormal3fv = ((void*)0);
 qglNormal3i = ((void*)0);
 qglNormal3iv = ((void*)0);
 qglNormal3s = ((void*)0);
 qglNormal3sv = ((void*)0);
 qglNormalPointer = ((void*)0);
 qglOrtho = ((void*)0);
 qglPassThrough = ((void*)0);
 qglPixelMapfv = ((void*)0);
 qglPixelMapuiv = ((void*)0);
 qglPixelMapusv = ((void*)0);
 qglPixelStoref = ((void*)0);
 qglPixelStorei = ((void*)0);
 qglPixelTransferf = ((void*)0);
 qglPixelTransferi = ((void*)0);
 qglPixelZoom = ((void*)0);
 qglPointSize = ((void*)0);
 qglPolygonMode = ((void*)0);
 qglPolygonOffset = ((void*)0);
 qglPolygonStipple = ((void*)0);
 qglPopAttrib = ((void*)0);
 qglPopClientAttrib = ((void*)0);
 qglPopMatrix = ((void*)0);
 qglPopName = ((void*)0);
 qglPrioritizeTextures = ((void*)0);
 qglPushAttrib = ((void*)0);
 qglPushClientAttrib = ((void*)0);
 qglPushMatrix = ((void*)0);
 qglPushName = ((void*)0);
 qglRasterPos2d = ((void*)0);
 qglRasterPos2dv = ((void*)0);
 qglRasterPos2f = ((void*)0);
 qglRasterPos2fv = ((void*)0);
 qglRasterPos2i = ((void*)0);
 qglRasterPos2iv = ((void*)0);
 qglRasterPos2s = ((void*)0);
 qglRasterPos2sv = ((void*)0);
 qglRasterPos3d = ((void*)0);
 qglRasterPos3dv = ((void*)0);
 qglRasterPos3f = ((void*)0);
 qglRasterPos3fv = ((void*)0);
 qglRasterPos3i = ((void*)0);
 qglRasterPos3iv = ((void*)0);
 qglRasterPos3s = ((void*)0);
 qglRasterPos3sv = ((void*)0);
 qglRasterPos4d = ((void*)0);
 qglRasterPos4dv = ((void*)0);
 qglRasterPos4f = ((void*)0);
 qglRasterPos4fv = ((void*)0);
 qglRasterPos4i = ((void*)0);
 qglRasterPos4iv = ((void*)0);
 qglRasterPos4s = ((void*)0);
 qglRasterPos4sv = ((void*)0);
 qglReadBuffer = ((void*)0);
 qglReadPixels = ((void*)0);
 qglRectd = ((void*)0);
 qglRectdv = ((void*)0);
 qglRectf = ((void*)0);
 qglRectfv = ((void*)0);
 qglRecti = ((void*)0);
 qglRectiv = ((void*)0);
 qglRects = ((void*)0);
 qglRectsv = ((void*)0);
 qglRenderMode = ((void*)0);
 qglRotated = ((void*)0);
 qglRotatef = ((void*)0);
 qglScaled = ((void*)0);
 qglScalef = ((void*)0);
 qglScissor = ((void*)0);
 qglSelectBuffer = ((void*)0);
 qglShadeModel = ((void*)0);
 qglStencilFunc = ((void*)0);
 qglStencilMask = ((void*)0);
 qglStencilOp = ((void*)0);
 qglTexCoord1d = ((void*)0);
 qglTexCoord1dv = ((void*)0);
 qglTexCoord1f = ((void*)0);
 qglTexCoord1fv = ((void*)0);
 qglTexCoord1i = ((void*)0);
 qglTexCoord1iv = ((void*)0);
 qglTexCoord1s = ((void*)0);
 qglTexCoord1sv = ((void*)0);
 qglTexCoord2d = ((void*)0);
 qglTexCoord2dv = ((void*)0);
 qglTexCoord2f = ((void*)0);
 qglTexCoord2fv = ((void*)0);
 qglTexCoord2i = ((void*)0);
 qglTexCoord2iv = ((void*)0);
 qglTexCoord2s = ((void*)0);
 qglTexCoord2sv = ((void*)0);
 qglTexCoord3d = ((void*)0);
 qglTexCoord3dv = ((void*)0);
 qglTexCoord3f = ((void*)0);
 qglTexCoord3fv = ((void*)0);
 qglTexCoord3i = ((void*)0);
 qglTexCoord3iv = ((void*)0);
 qglTexCoord3s = ((void*)0);
 qglTexCoord3sv = ((void*)0);
 qglTexCoord4d = ((void*)0);
 qglTexCoord4dv = ((void*)0);
 qglTexCoord4f = ((void*)0);
 qglTexCoord4fv = ((void*)0);
 qglTexCoord4i = ((void*)0);
 qglTexCoord4iv = ((void*)0);
 qglTexCoord4s = ((void*)0);
 qglTexCoord4sv = ((void*)0);
 qglTexCoordPointer = ((void*)0);
 qglTexEnvf = ((void*)0);
 qglTexEnvfv = ((void*)0);
 qglTexEnvi = ((void*)0);
 qglTexEnviv = ((void*)0);
 qglTexGend = ((void*)0);
 qglTexGendv = ((void*)0);
 qglTexGenf = ((void*)0);
 qglTexGenfv = ((void*)0);
 qglTexGeni = ((void*)0);
 qglTexGeniv = ((void*)0);
 qglTexImage1D = ((void*)0);
 qglTexImage2D = ((void*)0);
 qglTexParameterf = ((void*)0);
 qglTexParameterfv = ((void*)0);
 qglTexParameteri = ((void*)0);
 qglTexParameteriv = ((void*)0);
 qglTexSubImage1D = ((void*)0);
 qglTexSubImage2D = ((void*)0);
 qglTranslated = ((void*)0);
 qglTranslatef = ((void*)0);
 qglVertex2d = ((void*)0);
 qglVertex2dv = ((void*)0);
 qglVertex2f = ((void*)0);
 qglVertex2fv = ((void*)0);
 qglVertex2i = ((void*)0);
 qglVertex2iv = ((void*)0);
 qglVertex2s = ((void*)0);
 qglVertex2sv = ((void*)0);
 qglVertex3d = ((void*)0);
 qglVertex3dv = ((void*)0);
 qglVertex3f = ((void*)0);
 qglVertex3fv = ((void*)0);
 qglVertex3i = ((void*)0);
 qglVertex3iv = ((void*)0);
 qglVertex3s = ((void*)0);
 qglVertex3sv = ((void*)0);
 qglVertex4d = ((void*)0);
 qglVertex4dv = ((void*)0);
 qglVertex4f = ((void*)0);
 qglVertex4fv = ((void*)0);
 qglVertex4i = ((void*)0);
 qglVertex4iv = ((void*)0);
 qglVertex4s = ((void*)0);
 qglVertex4sv = ((void*)0);
 qglVertexPointer = ((void*)0);
 qglViewport = ((void*)0);
 qglXChooseVisual = ((void*)0);
 qglXCreateContext = ((void*)0);
 qglXDestroyContext = ((void*)0);
 qglXMakeCurrent = ((void*)0);
 qglXCopyContext = ((void*)0);
 qglXSwapBuffers = ((void*)0);
}
