
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 int CLEAR_PERI_REG_MASK (int ,int ) ;
 int DPORT_I2S0_CLK_EN ;
 int DPORT_PERIP_CLK_EN_REG ;
 int DPORT_SET_PERI_REG_MASK (int ,int ) ;
 int DPORT_WIFI_CLK_EN_REG ;
 int DPORT_WIFI_CLK_RNG_EN ;
 int I2S_CAMERA_EN ;
 int I2S_CONF2_REG (int ) ;
 int I2S_CONF_REG (int ) ;
 int I2S_DATA_ENABLE ;
 int I2S_DATA_ENABLE_TEST_EN ;
 int I2S_LCD_EN ;
 int I2S_RX_BCK_DIV_NUM ;
 int I2S_RX_BCK_DIV_NUM_S ;
 int I2S_RX_START ;
 int I2S_SAMPLE_RATE_CONF_REG (int ) ;
 int PERIPH_I2S0_MODULE ;
 int PERIPH_RNG_MODULE ;
 int RTC_CNTL_DTEST_RTC ;
 int RTC_CNTL_DTEST_RTC_S ;
 int RTC_CNTL_ENT_RTC ;
 int RTC_CNTL_TEST_MUX_REG ;
 int RTC_CNTL_ULP_CP_CTRL_REG ;
 int RTC_CNTL_ULP_CP_FORCE_START_TOP ;
 int RTC_CNTL_ULP_CP_START_TOP ;
 int SENS_FORCE_XPD_SAR ;
 int SENS_FORCE_XPD_SAR_S ;
 int SENS_SAR1_DIG_FORCE ;
 int SENS_SAR2_DIG_FORCE ;
 int SENS_SAR2_EN_TEST ;
 int SENS_SAR_MEAS1_MUX_REG ;
 int SENS_SAR_MEAS2_CTRL1_REG ;
 int SENS_SAR_MEAS_WAIT2_REG ;
 int SENS_SAR_POWER_XPD_SAR_REG ;
 int SENS_SAR_READ_CTRL2_REG ;
 int SENS_SAR_READ_CTRL_REG ;
 int SENS_SAR_START_FORCE_REG ;
 int SENS_ULP_CP_FORCE_START_TOP ;
 int SENS_ULP_CP_START_TOP ;
 int SET_PERI_REG_BITS (int ,int ,int,int ) ;
 int SET_PERI_REG_MASK (int ,int ) ;
 int SYSCON_SARADC_CTRL_REG ;
 int SYSCON_SARADC_DATA_SAR_SEL ;
 int SYSCON_SARADC_DATA_TO_I2S ;
 int SYSCON_SARADC_FSM_REG ;
 int SYSCON_SARADC_RSTB_WAIT ;
 int SYSCON_SARADC_RSTB_WAIT_S ;
 int SYSCON_SARADC_SAR2_MUX ;
 int SYSCON_SARADC_SAR2_PATT_TAB1_REG ;
 int SYSCON_SARADC_SAR2_PATT_TAB2_REG ;
 int SYSCON_SARADC_SAR2_PATT_TAB3_REG ;
 int SYSCON_SARADC_SAR2_PATT_TAB4_REG ;
 int SYSCON_SARADC_SAR_CLK_DIV ;
 int SYSCON_SARADC_SAR_CLK_DIV_S ;
 int SYSCON_SARADC_SAR_SEL ;
 int SYSCON_SARADC_START_WAIT ;
 int SYSCON_SARADC_START_WAIT_S ;
 int SYSCON_SARADC_WORK_MODE ;
 int SYSCON_SARADC_WORK_MODE_S ;
 int WRITE_PERI_REG (int ,int) ;
 int periph_module_enable (int ) ;

void bootloader_random_enable(void)
{






    periph_module_enable(PERIPH_RNG_MODULE);
    SET_PERI_REG_BITS(RTC_CNTL_TEST_MUX_REG, RTC_CNTL_DTEST_RTC, 2, RTC_CNTL_DTEST_RTC_S);
    SET_PERI_REG_MASK(RTC_CNTL_TEST_MUX_REG, RTC_CNTL_ENT_RTC);
    WRITE_PERI_REG(SYSCON_SARADC_SAR2_PATT_TAB1_REG, 0xADADADAD);
    WRITE_PERI_REG(SYSCON_SARADC_SAR2_PATT_TAB2_REG, 0xADADADAD);
    WRITE_PERI_REG(SYSCON_SARADC_SAR2_PATT_TAB3_REG, 0xADADADAD);
    WRITE_PERI_REG(SYSCON_SARADC_SAR2_PATT_TAB4_REG, 0xADADADAD);
    SET_PERI_REG_BITS(SYSCON_SARADC_CTRL_REG, SYSCON_SARADC_SAR_CLK_DIV, 4, SYSCON_SARADC_SAR_CLK_DIV_S);

    SET_PERI_REG_BITS(SYSCON_SARADC_FSM_REG, SYSCON_SARADC_RSTB_WAIT, 8, SYSCON_SARADC_RSTB_WAIT_S);



    SET_PERI_REG_BITS(SYSCON_SARADC_CTRL_REG, SYSCON_SARADC_WORK_MODE, 0, SYSCON_SARADC_WORK_MODE_S);
    SET_PERI_REG_MASK(SYSCON_SARADC_CTRL_REG, SYSCON_SARADC_SAR_SEL);
    CLEAR_PERI_REG_MASK(SYSCON_SARADC_CTRL_REG, SYSCON_SARADC_DATA_SAR_SEL);

    SET_PERI_REG_BITS(I2S_SAMPLE_RATE_CONF_REG(0), I2S_RX_BCK_DIV_NUM, 20, I2S_RX_BCK_DIV_NUM_S);

    SET_PERI_REG_MASK(SYSCON_SARADC_CTRL_REG, SYSCON_SARADC_DATA_TO_I2S);

    CLEAR_PERI_REG_MASK(I2S_CONF2_REG(0), I2S_CAMERA_EN);
    SET_PERI_REG_MASK(I2S_CONF2_REG(0), I2S_LCD_EN);
    SET_PERI_REG_MASK(I2S_CONF2_REG(0), I2S_DATA_ENABLE);
    SET_PERI_REG_MASK(I2S_CONF2_REG(0), I2S_DATA_ENABLE_TEST_EN);
    SET_PERI_REG_MASK(I2S_CONF_REG(0), I2S_RX_START);
}
