
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 int UV_E2BIG ;
 int UV_EACCES ;
 int UV_EADDRINUSE ;
 int UV_EADDRNOTAVAIL ;
 int UV_EAFNOSUPPORT ;
 int UV_EAGAIN ;
 int UV_EALREADY ;
 int UV_EBADF ;
 int UV_EBUSY ;
 int UV_ECANCELED ;
 int UV_ECHARSET ;
 int UV_ECONNABORTED ;
 int UV_ECONNREFUSED ;
 int UV_ECONNRESET ;
 int UV_EEXIST ;
 int UV_EFAULT ;
 int UV_EHOSTUNREACH ;
 int UV_EINVAL ;
 int UV_EIO ;
 int UV_EISCONN ;
 int UV_EISDIR ;
 int UV_ELOOP ;
 int UV_EMFILE ;
 int UV_EMSGSIZE ;
 int UV_ENAMETOOLONG ;
 int UV_ENETUNREACH ;
 int UV_ENOBUFS ;
 int UV_ENOENT ;
 int UV_ENOMEM ;
 int UV_ENOSPC ;
 int UV_ENOTCONN ;
 int UV_ENOTEMPTY ;
 int UV_ENOTSOCK ;
 int UV_ENOTSUP ;
 int UV_EOF ;
 int UV_EPERM ;
 int UV_EPIPE ;
 int UV_EPROTONOSUPPORT ;
 int UV_EROFS ;
 int UV_ETIMEDOUT ;
 int UV_EXDEV ;
 int UV_UNKNOWN ;
int uv_translate_sys_error(int sys_errno) {
  if (sys_errno <= 0) {
    return sys_errno;
  }

  switch (sys_errno) {
    case 177: return UV_EACCES;
    case 154: return UV_EACCES;
    case 204: return UV_EACCES;
    case 224: return UV_EADDRINUSE;
    case 153: return UV_EADDRINUSE;
    case 152: return UV_EADDRNOTAVAIL;
    case 151: return UV_EAFNOSUPPORT;
    case 130: return UV_EAGAIN;
    case 150: return UV_EALREADY;
    case 189: return UV_EBADF;
    case 187: return UV_EBADF;
    case 182: return UV_EBUSY;
    case 164: return UV_EBUSY;
    case 159: return UV_EBUSY;
    case 167: return UV_ECANCELED;
    case 144: return UV_ECANCELED;
    case 169: return UV_ECHARSET;
    case 214: return UV_ECONNABORTED;
    case 149: return UV_ECONNABORTED;
    case 213: return UV_ECONNREFUSED;
    case 148: return UV_ECONNREFUSED;
    case 179: return UV_ECONNRESET;
    case 147: return UV_ECONNRESET;
    case 223: return UV_EEXIST;
    case 198: return UV_EEXIST;
    case 218: return UV_EFAULT;
    case 146: return UV_EFAULT;
    case 194: return UV_EHOSTUNREACH;
    case 145: return UV_EHOSTUNREACH;
    case 193: return UV_EINVAL;
    case 191: return UV_EINVAL;
    case 185: return UV_EINVAL;
    case 157: return UV_EINVAL;
    case 143: return UV_EINVAL;
    case 135: return UV_EINVAL;
    case 132: return UV_EINVAL;
    case 220: return UV_EIO;
    case 217: return UV_EIO;
    case 212: return UV_EIO;
    case 211: return UV_EIO;
    case 210: return UV_EIO;
    case 207: return UV_EIO;
    case 201: return UV_EIO;
    case 200: return UV_EIO;
    case 196: return UV_EIO;
    case 192: return UV_EIO;
    case 183: return UV_EIO;
    case 171: return UV_EIO;
    case 170: return UV_EIO;
    case 168: return UV_EIO;
    case 160: return UV_EIO;
    case 158: return UV_EIO;
    case 142: return UV_EISCONN;
    case 215: return UV_ELOOP;
    case 156: return UV_EMFILE;
    case 141: return UV_EMFILE;
    case 140: return UV_EMSGSIZE;
    case 199: return UV_ENAMETOOLONG;
    case 178: return UV_ENETUNREACH;
    case 139: return UV_ENETUNREACH;
    case 138: return UV_ENOBUFS;
    case 222: return UV_ENOENT;
    case 209: return UV_ENOENT;
    case 202: return UV_ENOENT;
    case 197: return UV_ENOENT;
    case 186: return UV_ENOENT;
    case 190: return UV_ENOENT;
    case 184: return UV_ENOENT;
    case 180: return UV_ENOENT;
    case 165: return UV_ENOENT;
    case 129: return UV_ENOENT;
    case 128: return UV_ENOENT;
    case 175: return UV_ENOMEM;
    case 166: return UV_ENOMEM;
    case 216: return UV_ENOSPC;
    case 206: return UV_ENOSPC;
    case 205: return UV_ENOSPC;
    case 203: return UV_ENOSPC;
    case 195: return UV_ENOSPC;
    case 176: return UV_ENOTCONN;
    case 137: return UV_ENOTCONN;
    case 208: return UV_ENOTEMPTY;
    case 136: return UV_ENOTSOCK;
    case 173: return UV_ENOTSUP;
    case 219: return UV_EOF;
    case 225: return UV_EPERM;
    case 162: return UV_EPERM;
    case 221: return UV_EPIPE;
    case 172: return UV_EPIPE;
    case 163: return UV_EPIPE;
    case 133: return UV_EPIPE;
    case 134: return UV_EPROTONOSUPPORT;
    case 155: return UV_EROFS;
    case 161: return UV_ETIMEDOUT;
    case 131: return UV_ETIMEDOUT;
    case 174: return UV_EXDEV;
    case 188: return UV_EISDIR;
    case 181: return UV_E2BIG;
    default: return UV_UNKNOWN;
  }
}
