
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int u32 ;


 int RSN_CIPHER_SUITE_AES_128_CMAC ;
 int RSN_CIPHER_SUITE_BIP_CMAC_256 ;
 int RSN_CIPHER_SUITE_BIP_GMAC_128 ;
 int RSN_CIPHER_SUITE_BIP_GMAC_256 ;
 int RSN_CIPHER_SUITE_CCMP ;
 int RSN_CIPHER_SUITE_CCMP_256 ;
 int RSN_CIPHER_SUITE_GCMP ;
 int RSN_CIPHER_SUITE_GCMP_256 ;
 int RSN_CIPHER_SUITE_NONE ;
 int RSN_CIPHER_SUITE_NO_GROUP_ADDRESSED ;
 int RSN_CIPHER_SUITE_TKIP ;
 int WPA_CIPHER_AES_128_CMAC ;
 int WPA_CIPHER_BIP_CMAC_256 ;
 int WPA_CIPHER_BIP_GMAC_128 ;
 int WPA_CIPHER_BIP_GMAC_256 ;
 int WPA_CIPHER_CCMP ;
 int WPA_CIPHER_CCMP_256 ;
 int WPA_CIPHER_GCMP ;
 int WPA_CIPHER_GCMP_256 ;
 int WPA_CIPHER_GTK_NOT_USED ;
 int WPA_CIPHER_NONE ;
 int WPA_CIPHER_SUITE_CCMP ;
 int WPA_CIPHER_SUITE_NONE ;
 int WPA_CIPHER_SUITE_TKIP ;
 int WPA_CIPHER_TKIP ;
 int WPA_PROTO_RSN ;

u32 wpa_cipher_to_suite(int proto, int cipher)
{
 if (cipher & WPA_CIPHER_CCMP_256)
  return RSN_CIPHER_SUITE_CCMP_256;
 if (cipher & WPA_CIPHER_GCMP_256)
  return RSN_CIPHER_SUITE_GCMP_256;
 if (cipher & WPA_CIPHER_CCMP)
  return (proto == WPA_PROTO_RSN ?
   RSN_CIPHER_SUITE_CCMP : WPA_CIPHER_SUITE_CCMP);
 if (cipher & WPA_CIPHER_GCMP)
  return RSN_CIPHER_SUITE_GCMP;
 if (cipher & WPA_CIPHER_TKIP)
  return (proto == WPA_PROTO_RSN ?
   RSN_CIPHER_SUITE_TKIP : WPA_CIPHER_SUITE_TKIP);
 if (cipher & WPA_CIPHER_NONE)
  return (proto == WPA_PROTO_RSN ?
   RSN_CIPHER_SUITE_NONE : WPA_CIPHER_SUITE_NONE);
 if (cipher & WPA_CIPHER_GTK_NOT_USED)
  return RSN_CIPHER_SUITE_NO_GROUP_ADDRESSED;
 if (cipher & WPA_CIPHER_AES_128_CMAC)
  return RSN_CIPHER_SUITE_AES_128_CMAC;
 if (cipher & WPA_CIPHER_BIP_GMAC_128)
  return RSN_CIPHER_SUITE_BIP_GMAC_128;
 if (cipher & WPA_CIPHER_BIP_GMAC_256)
  return RSN_CIPHER_SUITE_BIP_GMAC_256;
 if (cipher & WPA_CIPHER_BIP_CMAC_256)
  return RSN_CIPHER_SUITE_BIP_CMAC_256;
 return 0;
}
