
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct pt_regs {int dummy; } ;


 int BLANK () ;
 int DEFINE (int ,int) ;
 int ENOSYS ;
 int ENOSYS_ ;
 int KTHREAD_SHIFT ;
 int KTHREAD_START_SP ;
 int NR_SYSCALLS_ ;
 int OFFSET (int ,int ,int ) ;
 int REGS_A0 ;
 int REGS_A1 ;
 int REGS_A10 ;
 int REGS_A11 ;
 int REGS_A12 ;
 int REGS_A13 ;
 int REGS_A14 ;
 int REGS_A15 ;
 int REGS_A16 ;
 int REGS_A17 ;
 int REGS_A18 ;
 int REGS_A19 ;
 int REGS_A2 ;
 int REGS_A20 ;
 int REGS_A21 ;
 int REGS_A22 ;
 int REGS_A23 ;
 int REGS_A24 ;
 int REGS_A25 ;
 int REGS_A26 ;
 int REGS_A27 ;
 int REGS_A28 ;
 int REGS_A29 ;
 int REGS_A3 ;
 int REGS_A30 ;
 int REGS_A31 ;
 int REGS_A4 ;
 int REGS_A5 ;
 int REGS_A6 ;
 int REGS_A7 ;
 int REGS_A8 ;
 int REGS_A9 ;
 int REGS_B0 ;
 int REGS_B1 ;
 int REGS_B10 ;
 int REGS_B11 ;
 int REGS_B12 ;
 int REGS_B13 ;
 int REGS_B16 ;
 int REGS_B17 ;
 int REGS_B18 ;
 int REGS_B19 ;
 int REGS_B2 ;
 int REGS_B20 ;
 int REGS_B21 ;
 int REGS_B22 ;
 int REGS_B23 ;
 int REGS_B24 ;
 int REGS_B25 ;
 int REGS_B26 ;
 int REGS_B27 ;
 int REGS_B28 ;
 int REGS_B29 ;
 int REGS_B3 ;
 int REGS_B30 ;
 int REGS_B31 ;
 int REGS_B4 ;
 int REGS_B5 ;
 int REGS_B6 ;
 int REGS_B7 ;
 int REGS_B8 ;
 int REGS_B9 ;
 int REGS_DP ;
 int REGS_ORIG_A4 ;
 int REGS_SP ;
 int REGS_TSR ;
 int REGS__END ;
 int TASK_STATE ;
 int THREAD_A11_10 ;
 int THREAD_A13_12 ;
 int THREAD_A15_14 ;
 int THREAD_B11_10 ;
 int THREAD_B13_12 ;
 int THREAD_B15_14 ;
 int THREAD_INFO_FLAGS ;
 int THREAD_INFO_PREEMPT_COUNT ;
 int THREAD_PC ;
 int THREAD_RICL_ICL ;
 int THREAD_SHIFT ;
 int THREAD_START_SP ;
 int TIF_ALLWORK_MASK ;
 int TIF_NEED_RESCHED ;
 int TIF_NOTIFY_RESUME ;
 int TIF_SIGPENDING ;
 int TIF_SYSCALL_TRACE ;
 int TIF_WORK_MASK ;
 int _TIF_ALLWORK_MASK ;
 int _TIF_NEED_RESCHED ;
 int _TIF_NOTIFY_RESUME ;
 int _TIF_SIGPENDING ;
 int _TIF_SYSCALL_TRACE ;
 int _TIF_WORK_MASK ;
 int __NR_syscalls ;
 int a0 ;
 int a1 ;
 int a10 ;
 int a11 ;
 int a11_10 ;
 int a12 ;
 int a13 ;
 int a13_12 ;
 int a14 ;
 int a15 ;
 int a15_14 ;
 int a16 ;
 int a17 ;
 int a18 ;
 int a19 ;
 int a2 ;
 int a20 ;
 int a21 ;
 int a22 ;
 int a23 ;
 int a24 ;
 int a25 ;
 int a26 ;
 int a27 ;
 int a28 ;
 int a29 ;
 int a3 ;
 int a30 ;
 int a31 ;
 int a4 ;
 int a5 ;
 int a6 ;
 int a7 ;
 int a8 ;
 int a9 ;
 int b0 ;
 int b1 ;
 int b10 ;
 int b11 ;
 int b11_10 ;
 int b12 ;
 int b13 ;
 int b13_12 ;
 int b15_14 ;
 int b16 ;
 int b17 ;
 int b18 ;
 int b19 ;
 int b2 ;
 int b20 ;
 int b21 ;
 int b22 ;
 int b23 ;
 int b24 ;
 int b25 ;
 int b26 ;
 int b27 ;
 int b28 ;
 int b29 ;
 int b3 ;
 int b30 ;
 int b31 ;
 int b4 ;
 int b5 ;
 int b6 ;
 int b7 ;
 int b8 ;
 int b9 ;
 int dp ;
 int flags ;
 int orig_a4 ;
 int pc ;
 int preempt_count ;
 int pt_regs ;
 int ricl_icl ;
 int sp ;
 int state ;
 int task_struct ;
 int thread_info ;
 int thread_struct ;
 int tsr ;

void foo(void)
{
 OFFSET(REGS_A16, pt_regs, a16);
 OFFSET(REGS_A17, pt_regs, a17);
 OFFSET(REGS_A18, pt_regs, a18);
 OFFSET(REGS_A19, pt_regs, a19);
 OFFSET(REGS_A20, pt_regs, a20);
 OFFSET(REGS_A21, pt_regs, a21);
 OFFSET(REGS_A22, pt_regs, a22);
 OFFSET(REGS_A23, pt_regs, a23);
 OFFSET(REGS_A24, pt_regs, a24);
 OFFSET(REGS_A25, pt_regs, a25);
 OFFSET(REGS_A26, pt_regs, a26);
 OFFSET(REGS_A27, pt_regs, a27);
 OFFSET(REGS_A28, pt_regs, a28);
 OFFSET(REGS_A29, pt_regs, a29);
 OFFSET(REGS_A30, pt_regs, a30);
 OFFSET(REGS_A31, pt_regs, a31);

 OFFSET(REGS_B16, pt_regs, b16);
 OFFSET(REGS_B17, pt_regs, b17);
 OFFSET(REGS_B18, pt_regs, b18);
 OFFSET(REGS_B19, pt_regs, b19);
 OFFSET(REGS_B20, pt_regs, b20);
 OFFSET(REGS_B21, pt_regs, b21);
 OFFSET(REGS_B22, pt_regs, b22);
 OFFSET(REGS_B23, pt_regs, b23);
 OFFSET(REGS_B24, pt_regs, b24);
 OFFSET(REGS_B25, pt_regs, b25);
 OFFSET(REGS_B26, pt_regs, b26);
 OFFSET(REGS_B27, pt_regs, b27);
 OFFSET(REGS_B28, pt_regs, b28);
 OFFSET(REGS_B29, pt_regs, b29);
 OFFSET(REGS_B30, pt_regs, b30);
 OFFSET(REGS_B31, pt_regs, b31);

 OFFSET(REGS_A0, pt_regs, a0);
 OFFSET(REGS_A1, pt_regs, a1);
 OFFSET(REGS_A2, pt_regs, a2);
 OFFSET(REGS_A3, pt_regs, a3);
 OFFSET(REGS_A4, pt_regs, a4);
 OFFSET(REGS_A5, pt_regs, a5);
 OFFSET(REGS_A6, pt_regs, a6);
 OFFSET(REGS_A7, pt_regs, a7);
 OFFSET(REGS_A8, pt_regs, a8);
 OFFSET(REGS_A9, pt_regs, a9);
 OFFSET(REGS_A10, pt_regs, a10);
 OFFSET(REGS_A11, pt_regs, a11);
 OFFSET(REGS_A12, pt_regs, a12);
 OFFSET(REGS_A13, pt_regs, a13);
 OFFSET(REGS_A14, pt_regs, a14);
 OFFSET(REGS_A15, pt_regs, a15);

 OFFSET(REGS_B0, pt_regs, b0);
 OFFSET(REGS_B1, pt_regs, b1);
 OFFSET(REGS_B2, pt_regs, b2);
 OFFSET(REGS_B3, pt_regs, b3);
 OFFSET(REGS_B4, pt_regs, b4);
 OFFSET(REGS_B5, pt_regs, b5);
 OFFSET(REGS_B6, pt_regs, b6);
 OFFSET(REGS_B7, pt_regs, b7);
 OFFSET(REGS_B8, pt_regs, b8);
 OFFSET(REGS_B9, pt_regs, b9);
 OFFSET(REGS_B10, pt_regs, b10);
 OFFSET(REGS_B11, pt_regs, b11);
 OFFSET(REGS_B12, pt_regs, b12);
 OFFSET(REGS_B13, pt_regs, b13);
 OFFSET(REGS_DP, pt_regs, dp);
 OFFSET(REGS_SP, pt_regs, sp);

 OFFSET(REGS_TSR, pt_regs, tsr);
 OFFSET(REGS_ORIG_A4, pt_regs, orig_a4);

 DEFINE(REGS__END, sizeof(struct pt_regs));
 BLANK();

 OFFSET(THREAD_PC, thread_struct, pc);
 OFFSET(THREAD_B15_14, thread_struct, b15_14);
 OFFSET(THREAD_A15_14, thread_struct, a15_14);
 OFFSET(THREAD_B13_12, thread_struct, b13_12);
 OFFSET(THREAD_A13_12, thread_struct, a13_12);
 OFFSET(THREAD_B11_10, thread_struct, b11_10);
 OFFSET(THREAD_A11_10, thread_struct, a11_10);
 OFFSET(THREAD_RICL_ICL, thread_struct, ricl_icl);
 BLANK();

 OFFSET(TASK_STATE, task_struct, state);
 BLANK();

 OFFSET(THREAD_INFO_FLAGS, thread_info, flags);
 OFFSET(THREAD_INFO_PREEMPT_COUNT, thread_info, preempt_count);
 BLANK();




 DEFINE(KTHREAD_SHIFT, THREAD_SHIFT);
 DEFINE(KTHREAD_START_SP, THREAD_START_SP);
 DEFINE(ENOSYS_, ENOSYS);
 DEFINE(NR_SYSCALLS_, __NR_syscalls);

 DEFINE(_TIF_SYSCALL_TRACE, (1<<TIF_SYSCALL_TRACE));
 DEFINE(_TIF_NOTIFY_RESUME, (1<<TIF_NOTIFY_RESUME));
 DEFINE(_TIF_SIGPENDING, (1<<TIF_SIGPENDING));
 DEFINE(_TIF_NEED_RESCHED, (1<<TIF_NEED_RESCHED));

 DEFINE(_TIF_ALLWORK_MASK, TIF_ALLWORK_MASK);
 DEFINE(_TIF_WORK_MASK, TIF_WORK_MASK);
}
