
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_3__ TYPE_1__ ;


typedef int rtc_sleep_pd_config_t ;
struct TYPE_3__ {int xtal_fpu; int bbpll_fpu; scalar_t__ cpu_waiti_clk_gate; scalar_t__ rtc_dboost_fpd; scalar_t__ pwrctl_init; scalar_t__ clkctl_init; int ck8m_wait; int pll_wait; } ;
typedef TYPE_1__ rtc_config_t ;


 int CLEAR_PERI_REG_MASK (int ,int) ;
 int DG_WRAP_POWERUP_CYCLES ;
 int DG_WRAP_WAIT_CYCLES ;
 int DPORT_CPU_PER_CONF_REG ;
 int DPORT_CPU_WAIT_MODE_FORCE_ON ;
 int DPORT_LSLP_MEM_PD_MASK ;
 int DPORT_MEM_PD_MASK_REG ;
 int DPORT_PRO_CACHE_MMU_MEM_FORCE_ON ;
 int DPORT_PRO_CACHE_MMU_POWER_CTRL_REG ;
 int DPORT_PRO_DCACHE_TAG_MEM_FORCE_ON ;
 int DPORT_PRO_DCACHE_TAG_POWER_CTRL_REG ;
 int DPORT_PRO_ICACHE_TAG_MEM_FORCE_ON ;
 int DPORT_PRO_ICACHE_TAG_POWER_CTRL_REG ;
 int DPORT_ROM_CTRL_0_REG ;
 int DPORT_ROM_FO ;
 int DPORT_SRAM_CTRL_0_REG ;
 int DPORT_SRAM_FO ;
 int REG_SET_FIELD (int ,int ,int ) ;
 int RTC_CNTL_ANA_CONF_REG ;
 int RTC_CNTL_BBPLL_FORCE_PU ;
 int RTC_CNTL_BBPLL_I2C_FORCE_PU ;
 int RTC_CNTL_BB_I2C_FORCE_PU ;
 int RTC_CNTL_BIAS_CONF_REG ;
 int RTC_CNTL_BIAS_FORCE_NOSLEEP ;
 int RTC_CNTL_BIAS_SLEEP_FOLW_8M ;
 int RTC_CNTL_CK8M_FORCE_PU ;
 int RTC_CNTL_CK8M_WAIT ;
 int RTC_CNTL_CLK_CONF_REG ;
 int RTC_CNTL_DBIAS_1V10 ;
 int RTC_CNTL_DBIAS_SLP ;
 int RTC_CNTL_DBIAS_WAK ;
 int RTC_CNTL_DBOOST_FORCE_PD ;
 int RTC_CNTL_DBOOST_FORCE_PU ;
 int RTC_CNTL_DEC_HEARTBEAT_WIDTH ;
 int RTC_CNTL_DG_PAD_AUTOHOLD_EN ;
 int RTC_CNTL_DG_PAD_FORCE_NOISO ;
 int RTC_CNTL_DG_PAD_FORCE_UNHOLD ;
 int RTC_CNTL_DG_WRAP_FORCE_NOISO ;
 int RTC_CNTL_DG_WRAP_FORCE_PU ;
 int RTC_CNTL_DG_WRAP_POWERUP_TIMER ;
 int RTC_CNTL_DG_WRAP_WAIT_TIMER ;
 int RTC_CNTL_DIG_ISO_REG ;
 int RTC_CNTL_DIG_PWC_REG ;
 int RTC_CNTL_FORCE_NOISO ;
 int RTC_CNTL_INC_HEARTBEAT_PERIOD ;
 int RTC_CNTL_MEM_FORCE_NOISO ;
 int RTC_CNTL_MEM_FORCE_PU ;
 int RTC_CNTL_MIN_SLP_VAL ;
 int RTC_CNTL_MIN_SLP_VAL_MIN ;
 int RTC_CNTL_OPTIONS0_REG ;
 int RTC_CNTL_PAD_AUTOHOLD_EN ;
 int RTC_CNTL_PAD_FORCE_NOISO ;
 int RTC_CNTL_PAD_FORCE_UNHOLD ;
 int RTC_CNTL_PLLA_FORCE_PD ;
 int RTC_CNTL_PLLA_FORCE_PU ;
 int RTC_CNTL_PLL_BUF_WAIT ;
 int RTC_CNTL_POWERUP_TIMER ;
 int RTC_CNTL_PVTMON_PU ;
 int RTC_CNTL_PWC_FORCE_PU ;
 int RTC_CNTL_PWC_REG ;
 int RTC_CNTL_REG ;
 int RTC_CNTL_REGULATOR_FORCE_PU ;
 int RTC_CNTL_RTCMEM_POWERUP_TIMER ;
 int RTC_CNTL_RTCMEM_WAIT_TIMER ;
 int RTC_CNTL_TIMER1_REG ;
 int RTC_CNTL_TIMER3_REG ;
 int RTC_CNTL_TIMER4_REG ;
 int RTC_CNTL_TIMER5_REG ;
 int RTC_CNTL_WAIT_TIMER ;
 int RTC_CNTL_WIFI_FORCE_NOISO ;
 int RTC_CNTL_WIFI_FORCE_PU ;
 int RTC_CNTL_WIFI_POWERUP_TIMER ;
 int RTC_CNTL_WIFI_WAIT_TIMER ;
 int RTC_CNTL_XTL_FORCE_PU ;
 int RTC_MEM_POWERUP_CYCLES ;
 int RTC_MEM_WAIT_CYCLES ;
 int RTC_POWERUP_CYCLES ;
 int RTC_SLEEP_PD_CONFIG_ALL (int ) ;
 int RTC_WAIT_CYCLES ;
 int SET_PERI_REG_MASK (int ,int) ;
 int SPI_MEM_CLK_EN ;
 int SPI_MEM_CLOCK_GATE_REG (int) ;
 int WIFI_POWERUP_CYCLES ;
 int WIFI_WAIT_CYCLES ;
 int rtc_clk_set_xtal_wait () ;
 int rtc_sleep_pd (int ) ;

void rtc_init(rtc_config_t cfg)
{
    CLEAR_PERI_REG_MASK(RTC_CNTL_ANA_CONF_REG, RTC_CNTL_PVTMON_PU);
    rtc_clk_set_xtal_wait();
    REG_SET_FIELD(RTC_CNTL_TIMER1_REG, RTC_CNTL_PLL_BUF_WAIT, cfg.pll_wait);
    REG_SET_FIELD(RTC_CNTL_TIMER1_REG, RTC_CNTL_CK8M_WAIT, cfg.ck8m_wait);



    REG_SET_FIELD(RTC_CNTL_TIMER5_REG, RTC_CNTL_MIN_SLP_VAL, RTC_CNTL_MIN_SLP_VAL_MIN);







    REG_SET_FIELD(RTC_CNTL_TIMER3_REG, RTC_CNTL_WIFI_POWERUP_TIMER, WIFI_POWERUP_CYCLES);
    REG_SET_FIELD(RTC_CNTL_TIMER3_REG, RTC_CNTL_WIFI_WAIT_TIMER, WIFI_WAIT_CYCLES);

    REG_SET_FIELD(RTC_CNTL_TIMER4_REG, RTC_CNTL_POWERUP_TIMER, RTC_POWERUP_CYCLES);
    REG_SET_FIELD(RTC_CNTL_TIMER4_REG, RTC_CNTL_WAIT_TIMER, RTC_WAIT_CYCLES);

    REG_SET_FIELD(RTC_CNTL_TIMER4_REG, RTC_CNTL_DG_WRAP_POWERUP_TIMER, DG_WRAP_POWERUP_CYCLES);
    REG_SET_FIELD(RTC_CNTL_TIMER4_REG, RTC_CNTL_DG_WRAP_WAIT_TIMER, DG_WRAP_WAIT_CYCLES);

    REG_SET_FIELD(RTC_CNTL_TIMER5_REG, RTC_CNTL_RTCMEM_POWERUP_TIMER, RTC_MEM_POWERUP_CYCLES);
    REG_SET_FIELD(RTC_CNTL_TIMER5_REG, RTC_CNTL_RTCMEM_WAIT_TIMER, RTC_MEM_WAIT_CYCLES);

    SET_PERI_REG_MASK(RTC_CNTL_BIAS_CONF_REG,
            RTC_CNTL_DEC_HEARTBEAT_WIDTH | RTC_CNTL_INC_HEARTBEAT_PERIOD);


    REG_SET_FIELD(RTC_CNTL_REG, RTC_CNTL_DBIAS_WAK, RTC_CNTL_DBIAS_1V10);
    REG_SET_FIELD(RTC_CNTL_REG, RTC_CNTL_DBIAS_SLP, RTC_CNTL_DBIAS_1V10);

    if (cfg.clkctl_init) {

        CLEAR_PERI_REG_MASK(DPORT_PRO_CACHE_MMU_POWER_CTRL_REG, DPORT_PRO_CACHE_MMU_MEM_FORCE_ON);

        REG_SET_FIELD(DPORT_ROM_CTRL_0_REG, DPORT_ROM_FO, 0);

        REG_SET_FIELD(DPORT_SRAM_CTRL_0_REG, DPORT_SRAM_FO, 0);

        CLEAR_PERI_REG_MASK(DPORT_PRO_DCACHE_TAG_POWER_CTRL_REG, DPORT_PRO_DCACHE_TAG_MEM_FORCE_ON);
        CLEAR_PERI_REG_MASK(DPORT_PRO_ICACHE_TAG_POWER_CTRL_REG, DPORT_PRO_ICACHE_TAG_MEM_FORCE_ON);

        CLEAR_PERI_REG_MASK(SPI_MEM_CLOCK_GATE_REG(0), SPI_MEM_CLK_EN);
        CLEAR_PERI_REG_MASK(SPI_MEM_CLOCK_GATE_REG(1), SPI_MEM_CLK_EN);
    }
    if (cfg.pwrctl_init) {
        CLEAR_PERI_REG_MASK(RTC_CNTL_CLK_CONF_REG, RTC_CNTL_CK8M_FORCE_PU);


        if (!(cfg.xtal_fpu | cfg.bbpll_fpu)) {
            CLEAR_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_XTL_FORCE_PU);
        } else {
            SET_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_XTL_FORCE_PU);
        }



        CLEAR_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BIAS_FORCE_NOSLEEP);



        SET_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BIAS_SLEEP_FOLW_8M);

        CLEAR_PERI_REG_MASK(RTC_CNTL_ANA_CONF_REG, RTC_CNTL_PLLA_FORCE_PU);
        SET_PERI_REG_MASK(RTC_CNTL_ANA_CONF_REG, RTC_CNTL_PLLA_FORCE_PD);


        if (!cfg.bbpll_fpu) {
            CLEAR_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BBPLL_FORCE_PU);
            CLEAR_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BBPLL_I2C_FORCE_PU);
            CLEAR_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BB_I2C_FORCE_PU);
        } else {
            SET_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BBPLL_FORCE_PU);
            SET_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BBPLL_I2C_FORCE_PU);
            SET_PERI_REG_MASK(RTC_CNTL_OPTIONS0_REG, RTC_CNTL_BB_I2C_FORCE_PU);
        }

        CLEAR_PERI_REG_MASK(RTC_CNTL_PWC_REG, RTC_CNTL_PWC_FORCE_PU);
        CLEAR_PERI_REG_MASK(RTC_CNTL_REG, RTC_CNTL_REGULATOR_FORCE_PU);
        CLEAR_PERI_REG_MASK(RTC_CNTL_REG, RTC_CNTL_DBOOST_FORCE_PU);


        CLEAR_PERI_REG_MASK(RTC_CNTL_PWC_REG, RTC_CNTL_MEM_FORCE_PU);
        CLEAR_PERI_REG_MASK(RTC_CNTL_PWC_REG, RTC_CNTL_MEM_FORCE_NOISO);

        if (cfg.rtc_dboost_fpd) {
            SET_PERI_REG_MASK(RTC_CNTL_REG, RTC_CNTL_DBOOST_FORCE_PD);
        } else {
            CLEAR_PERI_REG_MASK(RTC_CNTL_REG, RTC_CNTL_DBOOST_FORCE_PD);
        }

        CLEAR_PERI_REG_MASK(RTC_CNTL_PWC_REG, RTC_CNTL_MEM_FORCE_PU);



        CLEAR_PERI_REG_MASK(DPORT_MEM_PD_MASK_REG, DPORT_LSLP_MEM_PD_MASK);


        rtc_sleep_pd_config_t pd_cfg = RTC_SLEEP_PD_CONFIG_ALL(0);
        rtc_sleep_pd(pd_cfg);

        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_PWC_REG, RTC_CNTL_DG_WRAP_FORCE_PU);
        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_PWC_REG, RTC_CNTL_WIFI_FORCE_PU);


        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_ISO_REG, RTC_CNTL_DG_WRAP_FORCE_NOISO);
        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_ISO_REG, RTC_CNTL_WIFI_FORCE_NOISO);

        CLEAR_PERI_REG_MASK(RTC_CNTL_PWC_REG, RTC_CNTL_FORCE_NOISO);

        if (cfg.cpu_waiti_clk_gate){
            CLEAR_PERI_REG_MASK(DPORT_CPU_PER_CONF_REG, DPORT_CPU_WAIT_MODE_FORCE_ON);
        }
        else{
            SET_PERI_REG_MASK(DPORT_CPU_PER_CONF_REG, DPORT_CPU_WAIT_MODE_FORCE_ON);
        }






        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_ISO_REG, RTC_CNTL_DG_PAD_FORCE_UNHOLD);
        CLEAR_PERI_REG_MASK(RTC_CNTL_DIG_ISO_REG, RTC_CNTL_DG_PAD_FORCE_NOISO);




    }
}
