
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct intel_engine_cs {struct drm_i915_private* i915; } ;
struct i915_wa_list {int dummy; } ;
struct drm_i915_private {int dummy; } ;


 int CACHE_MODE_1 ;
 int COMMON_SLICE_CHICKEN2 ;
 int FLOW_CONTROL_ENABLE ;
 int GEN8_4x4_STC_OPTIMIZATION_DISABLE ;
 int GEN8_CS_CHICKEN1 ;
 int GEN8_ROW_CHICKEN ;
 int GEN8_SAMPLER_POWER_BYPASS_DIS ;
 int GEN8_ST_PO_DISABLE ;
 int GEN9_CCS_TLB_PREFETCH_ENABLE ;
 int GEN9_ENABLE_GPGPU_PREEMPTION ;
 int GEN9_ENABLE_YV12_BUGFIX ;
 int GEN9_FACTOR_IN_CLR_VAL_HIZ ;
 int GEN9_HALF_SLICE_CHICKEN5 ;
 int GEN9_HALF_SLICE_CHICKEN7 ;
 int GEN9_PARTIAL_RESOLVE_IN_VC_DISABLE ;
 int GEN9_PBE_COMPRESSED_HASH_SELECTION ;
 int GEN9_PREEMPT_3D_OBJECT_LEVEL ;
 int GEN9_PREEMPT_GPGPU_COMMAND_LEVEL ;
 int GEN9_PREEMPT_GPGPU_LEVEL_MASK ;
 int GEN9_SAMPLER_HASH_COMPRESSED_READ_ADDR ;
 int GEN9_WM_CHICKEN3 ;
 int HALF_SLICE_CHICKEN2 ;
 int HALF_SLICE_CHICKEN3 ;
 scalar_t__ HAS_LLC (struct drm_i915_private*) ;
 int HDC_CHICKEN0 ;
 int HDC_FORCE_CONTEXT_SAVE_RESTORE_NON_COHERENT ;
 int HDC_FORCE_CSR_NON_COHERENT_OVR_DISABLE ;
 int HDC_FORCE_NON_COHERENT ;
 scalar_t__ IS_COFFEELAKE (struct drm_i915_private*) ;
 scalar_t__ IS_GEN9_LP (struct drm_i915_private*) ;
 scalar_t__ IS_KABYLAKE (struct drm_i915_private*) ;
 scalar_t__ IS_SKYLAKE (struct drm_i915_private*) ;
 int PARTIAL_INSTRUCTION_SHOOTDOWN_DISABLE ;
 int WA_CLR_BIT_MASKED (int ,int ) ;
 int WA_SET_BIT_MASKED (int ,int) ;
 int WA_SET_FIELD_MASKED (int ,int ,int ) ;

__attribute__((used)) static void gen9_ctx_workarounds_init(struct intel_engine_cs *engine,
          struct i915_wa_list *wal)
{
 struct drm_i915_private *i915 = engine->i915;

 if (HAS_LLC(i915)) {





  WA_SET_BIT_MASKED(COMMON_SLICE_CHICKEN2,
      GEN9_PBE_COMPRESSED_HASH_SELECTION);
  WA_SET_BIT_MASKED(GEN9_HALF_SLICE_CHICKEN7,
      GEN9_SAMPLER_HASH_COMPRESSED_READ_ADDR);
 }



 WA_SET_BIT_MASKED(GEN8_ROW_CHICKEN,
     FLOW_CONTROL_ENABLE |
     PARTIAL_INSTRUCTION_SHOOTDOWN_DISABLE);



 WA_SET_BIT_MASKED(GEN9_HALF_SLICE_CHICKEN7,
     GEN9_ENABLE_YV12_BUGFIX |
     GEN9_ENABLE_GPGPU_PREEMPTION);



 WA_SET_BIT_MASKED(CACHE_MODE_1,
     GEN8_4x4_STC_OPTIMIZATION_DISABLE |
     GEN9_PARTIAL_RESOLVE_IN_VC_DISABLE);


 WA_CLR_BIT_MASKED(GEN9_HALF_SLICE_CHICKEN5,
     GEN9_CCS_TLB_PREFETCH_ENABLE);


 WA_SET_BIT_MASKED(HDC_CHICKEN0,
     HDC_FORCE_CONTEXT_SAVE_RESTORE_NON_COHERENT |
     HDC_FORCE_CSR_NON_COHERENT_OVR_DISABLE);
 WA_SET_BIT_MASKED(HDC_CHICKEN0,
     HDC_FORCE_NON_COHERENT);


 if (IS_SKYLAKE(i915) || IS_KABYLAKE(i915) || IS_COFFEELAKE(i915))
  WA_SET_BIT_MASKED(HALF_SLICE_CHICKEN3,
      GEN8_SAMPLER_POWER_BYPASS_DIS);


 WA_SET_BIT_MASKED(HALF_SLICE_CHICKEN2, GEN8_ST_PO_DISABLE);
 WA_CLR_BIT_MASKED(GEN8_CS_CHICKEN1, GEN9_PREEMPT_3D_OBJECT_LEVEL);


 WA_SET_FIELD_MASKED(GEN8_CS_CHICKEN1,
       GEN9_PREEMPT_GPGPU_LEVEL_MASK,
       GEN9_PREEMPT_GPGPU_COMMAND_LEVEL);


 if (IS_GEN9_LP(i915))
  WA_SET_BIT_MASKED(GEN9_WM_CHICKEN3, GEN9_FACTOR_IN_CLR_VAL_HIZ);
}
