; ModuleID = '/home/carl/AnghaBench/linux/drivers/scsi/bfa/extr_bfa_fcpim.c_bfa_fcpim_add_stats.c'
source_filename = "/home/carl/AnghaBench/linux/drivers/scsi/bfa/extr_bfa_fcpim.c_bfa_fcpim_add_stats.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.bfa_itnim_iostats_s = type { i32 }

@total_ios = common dso_local global i32 0, align 4
@qresumes = common dso_local global i32 0, align 4
@no_iotags = common dso_local global i32 0, align 4
@io_aborts = common dso_local global i32 0, align 4
@no_tskims = common dso_local global i32 0, align 4
@iocomp_ok = common dso_local global i32 0, align 4
@iocomp_underrun = common dso_local global i32 0, align 4
@iocomp_overrun = common dso_local global i32 0, align 4
@iocomp_aborted = common dso_local global i32 0, align 4
@iocomp_timedout = common dso_local global i32 0, align 4
@iocom_nexus_abort = common dso_local global i32 0, align 4
@iocom_proto_err = common dso_local global i32 0, align 4
@iocom_dif_err = common dso_local global i32 0, align 4
@iocom_sqer_needed = common dso_local global i32 0, align 4
@iocom_res_free = common dso_local global i32 0, align 4
@iocom_hostabrts = common dso_local global i32 0, align 4
@iocom_utags = common dso_local global i32 0, align 4
@io_cleanups = common dso_local global i32 0, align 4
@io_tmaborts = common dso_local global i32 0, align 4
@onlines = common dso_local global i32 0, align 4
@offlines = common dso_local global i32 0, align 4
@creates = common dso_local global i32 0, align 4
@deletes = common dso_local global i32 0, align 4
@create_comps = common dso_local global i32 0, align 4
@delete_comps = common dso_local global i32 0, align 4
@sler_events = common dso_local global i32 0, align 4
@fw_create = common dso_local global i32 0, align 4
@fw_delete = common dso_local global i32 0, align 4
@ioc_disabled = common dso_local global i32 0, align 4
@cleanup_comps = common dso_local global i32 0, align 4
@tm_cmnds = common dso_local global i32 0, align 4
@tm_fw_rsps = common dso_local global i32 0, align 4
@tm_success = common dso_local global i32 0, align 4
@tm_failures = common dso_local global i32 0, align 4
@tm_io_comps = common dso_local global i32 0, align 4
@tm_qresumes = common dso_local global i32 0, align 4
@tm_iocdowns = common dso_local global i32 0, align 4
@tm_cleanups = common dso_local global i32 0, align 4
@tm_cleanup_comps = common dso_local global i32 0, align 4
@io_comps = common dso_local global i32 0, align 4
@input_reqs = common dso_local global i32 0, align 4
@output_reqs = common dso_local global i32 0, align 4
@rd_throughput = common dso_local global i32 0, align 4
@wr_throughput = common dso_local global i32 0, align 4

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @bfa_fcpim_add_stats(%struct.bfa_itnim_iostats_s* %0, %struct.bfa_itnim_iostats_s* %1) #0 {
  %3 = alloca %struct.bfa_itnim_iostats_s*, align 8
  %4 = alloca %struct.bfa_itnim_iostats_s*, align 8
  store %struct.bfa_itnim_iostats_s* %0, %struct.bfa_itnim_iostats_s** %3, align 8
  store %struct.bfa_itnim_iostats_s* %1, %struct.bfa_itnim_iostats_s** %4, align 8
  %5 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %6 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %7 = load i32, i32* @total_ios, align 4
  %8 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %5, %struct.bfa_itnim_iostats_s* %6, i32 %7)
  %9 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %10 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %11 = load i32, i32* @qresumes, align 4
  %12 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %9, %struct.bfa_itnim_iostats_s* %10, i32 %11)
  %13 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %14 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %15 = load i32, i32* @no_iotags, align 4
  %16 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %13, %struct.bfa_itnim_iostats_s* %14, i32 %15)
  %17 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %18 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %19 = load i32, i32* @io_aborts, align 4
  %20 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %17, %struct.bfa_itnim_iostats_s* %18, i32 %19)
  %21 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %22 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %23 = load i32, i32* @no_tskims, align 4
  %24 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %21, %struct.bfa_itnim_iostats_s* %22, i32 %23)
  %25 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %26 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %27 = load i32, i32* @iocomp_ok, align 4
  %28 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %25, %struct.bfa_itnim_iostats_s* %26, i32 %27)
  %29 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %30 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %31 = load i32, i32* @iocomp_underrun, align 4
  %32 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %29, %struct.bfa_itnim_iostats_s* %30, i32 %31)
  %33 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %34 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %35 = load i32, i32* @iocomp_overrun, align 4
  %36 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %33, %struct.bfa_itnim_iostats_s* %34, i32 %35)
  %37 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %38 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %39 = load i32, i32* @iocomp_aborted, align 4
  %40 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %37, %struct.bfa_itnim_iostats_s* %38, i32 %39)
  %41 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %42 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %43 = load i32, i32* @iocomp_timedout, align 4
  %44 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %41, %struct.bfa_itnim_iostats_s* %42, i32 %43)
  %45 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %46 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %47 = load i32, i32* @iocom_nexus_abort, align 4
  %48 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %45, %struct.bfa_itnim_iostats_s* %46, i32 %47)
  %49 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %50 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %51 = load i32, i32* @iocom_proto_err, align 4
  %52 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %49, %struct.bfa_itnim_iostats_s* %50, i32 %51)
  %53 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %54 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %55 = load i32, i32* @iocom_dif_err, align 4
  %56 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %53, %struct.bfa_itnim_iostats_s* %54, i32 %55)
  %57 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %58 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %59 = load i32, i32* @iocom_sqer_needed, align 4
  %60 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %57, %struct.bfa_itnim_iostats_s* %58, i32 %59)
  %61 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %62 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %63 = load i32, i32* @iocom_res_free, align 4
  %64 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %61, %struct.bfa_itnim_iostats_s* %62, i32 %63)
  %65 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %66 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %67 = load i32, i32* @iocom_hostabrts, align 4
  %68 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %65, %struct.bfa_itnim_iostats_s* %66, i32 %67)
  %69 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %70 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %71 = load i32, i32* @iocom_utags, align 4
  %72 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %69, %struct.bfa_itnim_iostats_s* %70, i32 %71)
  %73 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %74 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %75 = load i32, i32* @io_cleanups, align 4
  %76 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %73, %struct.bfa_itnim_iostats_s* %74, i32 %75)
  %77 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %78 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %79 = load i32, i32* @io_tmaborts, align 4
  %80 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %77, %struct.bfa_itnim_iostats_s* %78, i32 %79)
  %81 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %82 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %83 = load i32, i32* @onlines, align 4
  %84 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %81, %struct.bfa_itnim_iostats_s* %82, i32 %83)
  %85 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %86 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %87 = load i32, i32* @offlines, align 4
  %88 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %85, %struct.bfa_itnim_iostats_s* %86, i32 %87)
  %89 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %90 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %91 = load i32, i32* @creates, align 4
  %92 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %89, %struct.bfa_itnim_iostats_s* %90, i32 %91)
  %93 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %94 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %95 = load i32, i32* @deletes, align 4
  %96 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %93, %struct.bfa_itnim_iostats_s* %94, i32 %95)
  %97 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %98 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %99 = load i32, i32* @create_comps, align 4
  %100 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %97, %struct.bfa_itnim_iostats_s* %98, i32 %99)
  %101 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %102 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %103 = load i32, i32* @delete_comps, align 4
  %104 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %101, %struct.bfa_itnim_iostats_s* %102, i32 %103)
  %105 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %106 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %107 = load i32, i32* @sler_events, align 4
  %108 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %105, %struct.bfa_itnim_iostats_s* %106, i32 %107)
  %109 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %110 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %111 = load i32, i32* @fw_create, align 4
  %112 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %109, %struct.bfa_itnim_iostats_s* %110, i32 %111)
  %113 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %114 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %115 = load i32, i32* @fw_delete, align 4
  %116 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %113, %struct.bfa_itnim_iostats_s* %114, i32 %115)
  %117 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %118 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %119 = load i32, i32* @ioc_disabled, align 4
  %120 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %117, %struct.bfa_itnim_iostats_s* %118, i32 %119)
  %121 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %122 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %123 = load i32, i32* @cleanup_comps, align 4
  %124 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %121, %struct.bfa_itnim_iostats_s* %122, i32 %123)
  %125 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %126 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %127 = load i32, i32* @tm_cmnds, align 4
  %128 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %125, %struct.bfa_itnim_iostats_s* %126, i32 %127)
  %129 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %130 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %131 = load i32, i32* @tm_fw_rsps, align 4
  %132 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %129, %struct.bfa_itnim_iostats_s* %130, i32 %131)
  %133 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %134 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %135 = load i32, i32* @tm_success, align 4
  %136 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %133, %struct.bfa_itnim_iostats_s* %134, i32 %135)
  %137 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %138 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %139 = load i32, i32* @tm_failures, align 4
  %140 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %137, %struct.bfa_itnim_iostats_s* %138, i32 %139)
  %141 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %142 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %143 = load i32, i32* @tm_io_comps, align 4
  %144 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %141, %struct.bfa_itnim_iostats_s* %142, i32 %143)
  %145 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %146 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %147 = load i32, i32* @tm_qresumes, align 4
  %148 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %145, %struct.bfa_itnim_iostats_s* %146, i32 %147)
  %149 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %150 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %151 = load i32, i32* @tm_iocdowns, align 4
  %152 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %149, %struct.bfa_itnim_iostats_s* %150, i32 %151)
  %153 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %154 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %155 = load i32, i32* @tm_cleanups, align 4
  %156 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %153, %struct.bfa_itnim_iostats_s* %154, i32 %155)
  %157 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %158 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %159 = load i32, i32* @tm_cleanup_comps, align 4
  %160 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %157, %struct.bfa_itnim_iostats_s* %158, i32 %159)
  %161 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %162 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %163 = load i32, i32* @io_comps, align 4
  %164 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %161, %struct.bfa_itnim_iostats_s* %162, i32 %163)
  %165 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %166 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %167 = load i32, i32* @input_reqs, align 4
  %168 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %165, %struct.bfa_itnim_iostats_s* %166, i32 %167)
  %169 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %170 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %171 = load i32, i32* @output_reqs, align 4
  %172 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %169, %struct.bfa_itnim_iostats_s* %170, i32 %171)
  %173 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %174 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %175 = load i32, i32* @rd_throughput, align 4
  %176 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %173, %struct.bfa_itnim_iostats_s* %174, i32 %175)
  %177 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %3, align 8
  %178 = load %struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s** %4, align 8
  %179 = load i32, i32* @wr_throughput, align 4
  %180 = call i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s* %177, %struct.bfa_itnim_iostats_s* %178, i32 %179)
  ret void
}

declare dso_local i32 @bfa_fcpim_add_iostats(%struct.bfa_itnim_iostats_s*, %struct.bfa_itnim_iostats_s*, i32) #1

attributes #0 = { noinline nounwind optnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.1 (https://github.com/wsmoses/llvm-project-tok c8e5003577614e72d6d18a216e6a09771e1fcce4)"}
