
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int D3D_BLOB_PART ;


 int D3D_BLOB_ALL_SIGNATURE_BLOB ;
 int D3D_BLOB_DEBUG_INFO ;
 int D3D_BLOB_INPUT_AND_OUTPUT_SIGNATURE_BLOB ;
 int D3D_BLOB_INPUT_SIGNATURE_BLOB ;
 int D3D_BLOB_LEGACY_SHADER ;
 int D3D_BLOB_OUTPUT_SIGNATURE_BLOB ;
 int D3D_BLOB_PATCH_CONSTANT_SIGNATURE_BLOB ;
 int D3D_BLOB_TEST_ALTERNATE_SHADER ;
 int D3D_BLOB_TEST_COMPILE_DETAILS ;
 int D3D_BLOB_TEST_COMPILE_PERF ;
 int D3D_BLOB_XNA_PREPASS_SHADER ;
 int D3D_BLOB_XNA_SHADER ;
 int FIXME (char*,int) ;
 int WINE_D3DCOMPILER_TO_STR (int ) ;

const char *debug_d3dcompiler_d3d_blob_part(D3D_BLOB_PART part)
{
    switch(part)
    {
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_INPUT_SIGNATURE_BLOB);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_OUTPUT_SIGNATURE_BLOB);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_INPUT_AND_OUTPUT_SIGNATURE_BLOB);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_PATCH_CONSTANT_SIGNATURE_BLOB);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_ALL_SIGNATURE_BLOB);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_DEBUG_INFO);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_LEGACY_SHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_XNA_PREPASS_SHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_XNA_SHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_TEST_ALTERNATE_SHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_TEST_COMPILE_DETAILS);
        WINE_D3DCOMPILER_TO_STR(D3D_BLOB_TEST_COMPILE_PERF);
        default:
            FIXME("Unrecognized D3D_BLOB_PART %#x\n", part);
            return "unrecognized";
    }
}
