
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int D3D_SHADER_VARIABLE_TYPE ;


 int D3D_SVT_APPEND_STRUCTURED_BUFFER ;
 int D3D_SVT_BLEND ;
 int D3D_SVT_BOOL ;
 int D3D_SVT_BUFFER ;
 int D3D_SVT_BYTEADDRESS_BUFFER ;
 int D3D_SVT_CBUFFER ;
 int D3D_SVT_COMPUTESHADER ;
 int D3D_SVT_CONSUME_STRUCTURED_BUFFER ;
 int D3D_SVT_DEPTHSTENCIL ;
 int D3D_SVT_DEPTHSTENCILVIEW ;
 int D3D_SVT_DOMAINSHADER ;
 int D3D_SVT_DOUBLE ;
 int D3D_SVT_FLOAT ;
 int D3D_SVT_GEOMETRYSHADER ;
 int D3D_SVT_HULLSHADER ;
 int D3D_SVT_INT ;
 int D3D_SVT_INTERFACE_POINTER ;
 int D3D_SVT_PIXELSHADER ;
 int D3D_SVT_RASTERIZER ;
 int D3D_SVT_RENDERTARGETVIEW ;
 int D3D_SVT_RWBUFFER ;
 int D3D_SVT_RWBYTEADDRESS_BUFFER ;
 int D3D_SVT_RWSTRUCTURED_BUFFER ;
 int D3D_SVT_RWTEXTURE1D ;
 int D3D_SVT_RWTEXTURE1DARRAY ;
 int D3D_SVT_RWTEXTURE2D ;
 int D3D_SVT_RWTEXTURE2DARRAY ;
 int D3D_SVT_RWTEXTURE3D ;
 int D3D_SVT_SAMPLER ;
 int D3D_SVT_STRING ;
 int D3D_SVT_STRUCTURED_BUFFER ;
 int D3D_SVT_TBUFFER ;
 int D3D_SVT_TEXTURE ;
 int D3D_SVT_TEXTURE1D ;
 int D3D_SVT_TEXTURE1DARRAY ;
 int D3D_SVT_TEXTURE2D ;
 int D3D_SVT_TEXTURE2DARRAY ;
 int D3D_SVT_TEXTURE2DMS ;
 int D3D_SVT_TEXTURE2DMSARRAY ;
 int D3D_SVT_TEXTURE3D ;
 int D3D_SVT_TEXTURECUBE ;
 int D3D_SVT_TEXTURECUBEARRAY ;
 int D3D_SVT_UINT ;
 int D3D_SVT_UINT8 ;
 int D3D_SVT_VERTEXSHADER ;
 int D3D_SVT_VOID ;
 int FIXME (char*,int) ;
 int WINE_D3DCOMPILER_TO_STR (int ) ;

const char *debug_d3dcompiler_shader_variable_type(D3D_SHADER_VARIABLE_TYPE t)
{
    switch (t)
    {
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_VOID);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_BOOL);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_INT);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_FLOAT);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_STRING);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE1D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE2D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE3D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURECUBE);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_SAMPLER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_PIXELSHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_VERTEXSHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_UINT);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_UINT8);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_GEOMETRYSHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RASTERIZER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_DEPTHSTENCIL);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_BLEND);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_CBUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TBUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE1DARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE2DARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RENDERTARGETVIEW);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_DEPTHSTENCILVIEW);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE2DMS);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURE2DMSARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_TEXTURECUBEARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_HULLSHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_DOMAINSHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_INTERFACE_POINTER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_COMPUTESHADER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_DOUBLE);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWTEXTURE1D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWTEXTURE1DARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWTEXTURE2D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWTEXTURE2DARRAY);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWTEXTURE3D);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWBUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_BYTEADDRESS_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWBYTEADDRESS_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_STRUCTURED_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_RWSTRUCTURED_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_APPEND_STRUCTURED_BUFFER);
        WINE_D3DCOMPILER_TO_STR(D3D_SVT_CONSUME_STRUCTURED_BUFFER);
        default:
            FIXME("Unrecognized D3D_SHADER_VARIABLE_TYPE %#x.\n", t);
            return "unrecognized";
    }
}
